### ISSUE TITLE
PNG incomplets (corrompus) font planter la mise en lot (PDF) en sortie

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#108]
**Description du problème**
Lorsqu'un utilisateur transmet une pièce jointe qui est tronquée, incomplète, celle-ci reste coincé dans la transmission en sortie.

**Étapes pour reproduire le bogue**
1. Transmettre un png ou jpg qui aurait été altéré.
2. Soumettre le formulaire
3. ça reste coincé 

**Comportement attendu**
L'utilisateur devrait être avisé que l'image transmise est défectueuse et être bloqué.

**Captures écran**
Si applicable, des captures d'écran démontrant le problème.

**Appareil utilisé/fureteur utilisé**
 - OS: (ex: Windows 10)
 - Fureteur: (ex: Chrome 111)

**Autres informations**
- Version de l'application FRW (inscrite au bas de la page)
- Date/heure de l'événement (au plus précis possible)

AB#58449

**Comment by anisite** [comment]
branche refuser-jpg-png-invalides déjà existante

**Comment by anisite** [comment]
C'est en IT

**Comment by loima02** [comment]
C'est en PROD
