### ISSUE TITLE
Ajouter la possibilité de tester la reprise (préremplissage) à partir de l'interface de test de FRW

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#110]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Il est impossible de tester la reprise à partir des outils de tests de FRW

**Décrivez votre besoin**
Ajouter un toggle, un accordéon, onglet, ou autre pour changer l'interface (page d'Accueil) de FRW pour tester la reprise d'un formulaire (donc conserver le bloc de json pour permettre le préremplissage)

**Décrivez les alternatives que vous avez envisagées**
Utiliser ECS, mais ça ne permet pas tout.

**Propostion de solution**
Permettre de saisir un id de formulaire (ou autre, selon les analystes), bypasser la sécurité pour ne pas avoir à se soucier de qui était l'utilisateur qui avait démarré le formulaire initialement. 

**Contexte supplémentaire**
Cela va permettre de façon simple de tester la reprise et n'ajoutera pas de grande complexité.

[AB#73281](https://devops700.itp.extra/700/TPM/_workitems/edit/73281)

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
