### ISSUE TITLE
Ajouter la possibilité de personnaliser le message de déconnexion

### ISSUE THREAD

**Issue by maximpouliot** [MTESSDev/FRW#117]
**Décrivez votre besoin**
Nous ne pouvons pas rediriger l'utilisateur vers mon Dossier (Retraite Québec) une fois qu'il est déconnecté

**Décrivez les alternatives que vous avez envisagées**
Notifier le client au début du formulaire

**Propostion de solution**
De pouvoir personnaliser le message de déconnexion 

AB#59237

**Comment by Ghost3044** [comment]
Bonjour,

Dans un soucis d'uniformité de la solution, nous ne voulons pas permettre de personnaliser ce texte.

Je suis disponible si vous avez des questions.
