### ISSUE TITLE
Erreurs en lien avec Google Analytics dans la console du navigateur dans les formulaires du système ECS

### ISSUE THREAD

**Issue by LarcM7** [MTESSDev/FRW#118]
**Description du problème**
Des erreurs en lien avec Google Analytics apparaissent dans la console lorsqu'on navigue dans un formulaire du système ECS.

**Étapes pour reproduire le bogue**
1. Ouvrir un formulaire ECS
2. Ouvrir la console du navigateur (F12)
3. Naviguer dedans, répondre à des questions

**Comportement attendu**
Normalement il n'y aurait aucune erreur.

**Captures écran**
![image](https://github.com/MTESSDev/FRW/assets/129791924/4c2ec89f-29b5-450b-a144-4a8847574977)

**Appareil utilisé/fureteur utilisé**
Windows + Chrome

**Pistes de solutions**
- Peut-être que Google a changé son url du produit
- Peut-être que la DCOM a activé la nouvelle structure
- Changer les règles de contenu dans la config
- La config du système autorisé ECS call le googletag manager, qui lui appelle d'autres scripts qui ont peut-être changé d'url
- Essayer d'ajouter https://analytics.google.com ou https://*.google.com, et/ou essayer d'enlever https://www.google-analytics.com vu que ça sert pu

[AB#73311](https://devops700.itp.extra/700/TPM/_workitems/edit/73311)

**Comment by Ghost3044** [comment]
test

**Comment by anisite** [comment]
Ajouter statweb.dev et statweb pour RQ aussi @Quasar-0 Merci

**Comment by loima02** [comment]
C'est en IT!
