### ISSUE TITLE
accents tolérés dans champ courriel

### ISSUE THREAD

**Issue by LarcM7** [MTESSDev/FRW#120]
**Description du problème**
Les accents sont tolérés dans le champ de type email. Cela peut faire planter l'orchestration avec le message _"No":"500","Message":"La liste de destinataires contient un ou plusieurs adresses invalides. Veuillez les corriger afin de continuer."_

**Étapes pour reproduire le bogue**
mettre un accent dans l'adresse courriel

**Comportement attendu**
valider s'il y a un accent ou non et lever une validation si c'est le cas

**Captures écran**
![image](https://github.com/MTESSDev/FRW/assets/129791924/01587980-a8a3-4c7f-bdd9-2b1e53bc214d)

**Appareil utilisé/fureteur utilisé**
 - windows + chrome

[AB#73326](https://devops700.itp.extra/700/TPM/_workitems/edit/73326)

**Comment by anisite** [comment]
finalement un fix sera effectué @loima02

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
