### ISSUE TITLE
Champ obligatoire se vide après validation d'un formulaire d'aiguillage

### ISSUE THREAD

**Issue by jodionrq** [MTESSDev/FRW#129]
Un champ de date remplit dans un formulaire d'aiguillage devient vide, comme si on ne l'avait pas remplit au moment de valider le formulaire d'aiguillage. une erreur est alors signalée et il est impossible de passer au formulaire standard.

**Étapes pour reproduire le bogue**
1. Aller à : https://formulaires.it.mtess.gouv.qc.ca/240002?s=F995D56C-D659-4FF7-A650-D7A8C3DDAC36
2. Cliquer sur 'RSP-079-001-AIG'
3. Remplir les champs (cette séquence est la plus simple, mais le bogue se produit peu importe les choix)
   - Remplissez-vous cette demande pour vous? Oui
   - Indiquez le régime... : Prendre n'importe quel
   - Quel est l'objet de votre demande? Demande de prestation...
   - Souhaitez-vous racheter... Non
   - Cocher la case
   - Date à laquelle... : Choisir une date
5. Lorsqu'on clique sur "Suivant" la validation se fait, mais on indique que le champ "Date à laquelle..." est obligatoire, car il s'est vidé!

**Comportement attendu**
Les champs remplis ne devraient pas se vider.

**Captures écran**
![image](https://github.com/MTESSDev/FRW/assets/124822406/ab63898f-ff03-45d9-bbc9-ae7c33adac19)

![image](https://github.com/MTESSDev/FRW/assets/124822406/f385354b-656a-45f4-9cda-ec48d74a6913)

**Appareil utilisé/fureteur utilisé**
 - OS: ex: Windows 10
 - Fureteur: Edge Version 114.0.1823.86 (64 bits) et Chrome

AB#61106

**Comment by jodionrq** [comment]
Bonjour, effectivement en ajustant le tout ça fonctionne.
C'est drôle car dans certaines autres occasions j'ai un bouton radio que je répétais dans deux conditions v-if différentes, selon s'il apparaissait à un moment ou un autre après avoir répondu à certaines questions et ça ne semblait pas causer de problème.
Dans tous les cas, je garde cette notion en tête. 
Merci!

**Comment by jodionrq** [comment]
Bonjour, le problème semblait être réglé, mais est revenu suite à une nouvelle version. J'ai changé tout le nom pour être certain que tout ce qui avec le tag "name:" n'était pas en double.
Je me retrouve encore avec le même problème.
Est-ce que ça peut être dû à autre chose?

**Comment by jodionrq** [comment]
Bonjour,
J'ai changé tous les noms des options 'on' et 'off' qui se répétaient dans mes boutons radio et j'ai toujours le même bug.
Avez-vous une autre piste de solution?

**Comment by j0ber** [comment]
C'est surement une erreur dans votre fichier de config...

Est-ce encore les mêmes étapes pour reproduire le problème?
Retransmettez votre fichier et indiquez nous clairement le problème.

Là on ne peut rien faire sinon.

**Comment by jodionrq** [comment]
Bonjour, Il s'agit bien du formulaire RSP-079-001-AIG à cet endroit
https://formulaires.it.mtess.gouv.qc.ca/240002?s=F995D56C-D659-4FF7-A650-D7A8C3DDAC36
![image](https://github.com/MTESSDev/FRW/assets/124822406/381d697d-1ab1-4301-8557-316aba4ea57f)
Voici les étapes à suivre :
1. Remplissez-vous cette demande pour vous? Oui
2. Indiquez le régime pour lequel vous présentez cette demande : (Choisir n'importe lequel)
3. Quel est l'objet de votre demande? Demande de transfert de la rente différée
4. Date à laquelle vous avez mis ou prévoyez mettre fin à votre emploi : (Mettre n'importe quelle date)
5. Vous devez avoir moins de 55 ans pour demander... : Oui
6. Cliquer sur "Suivant"

Lors de la validation, le champ au point 5 s'inscrit comme n'ayant pas été rempli.
Je peux vous fournir le fichier yaml au besoin et vous pouvez me rejoindre via Teams pour plus d'explications.

Merci!

**Comment by j0ber** [comment]
Bonjour,

Cette fois vous avez mis le doigt sur un problème. Lors de la révision, une validation serveur est effectuée et une épuration du modèle de données est effectuée (ex. un champ avec un v-if qui ne serait plus visible sera supprimé du modèle).

Il semble qu'il y ait un problème avec cette fonction de nettoyage lorsqu'un v-if utilise une "computed". Dans cette situation le champ est systématiquement retiré du modèle.

Nous devrions être en mesure de regarder ce qui peut être fait pour corriger le problème dans 2 semaines. 

Selon votre niveau d'urgence, il y a cependant une solution de contournement possible. Elle consiste à créer un champ caché (hidden) qui contiendra la valeur retournée par la "computed" via une "watch" sur cette "computed". Vos "v-if" utiliseront la valeur du champ caché, au lieu de la "computed".
Ce n'est pas très compliqué bien que ça puisse le paraître, cependant ça fonctionne si vous êtes pressé. 

Si vous êtes pressé et avez besoin de plus de détails sur cette solution, revenez-moi.

L'issue reste ouvert et nous allons le regarder dans environ 2 semaines.

**Comment by jodionrq** [comment]
Bonjour, merci pour les explications, c'est très clair.
Comme il n'y a pas d'urgence, nous pouvons attendre la solution dans 2 semaines.
Merci encore pour votre assistance, c'est très apprécié!
Bonne journée

**Comment by j0ber** [comment]
Nous allons regarder dans 2 semaines, la solution ne serait **pas nécessairement disponible dans 2 semaines**, mais à ce moment on sera à mesure de confirmer si une solution est possible ou non et sa date d'implantation.
Bonne journée!

**Comment by florentarneodo** [comment]
Bonjour,
C'est pour faire un suivi.
Merci et bonne journée :)

**Comment by j0ber** [comment]
Bonjour,
Malheureusement nous avons actuellement une urgence qui va nous occuper jusqu'au début octobre.
Je vous suggère d'utiliser la solution de contournement mentionnée pour l'instant.
Nous allons regarder cela dès que possible.

Bonne journée!

**Comment by ageliinas** [comment]
Bonjour,

J'ai essayé de mettre nbJoursRetraite dans les méthodes à la place des computed comme mentionné, mais sans même l'avoir mis en ligne, aucune de mes validations fonctionnent en faisant ça à date.

**Comment by j0ber** [comment]
quand vous utilisez nbJoursRetraite vous avez bien mis les parenthèses ? (car ce n'est plus une computed)  Lors de l'utilisation il faut utiliser nbJoursRetraite()

**Comment by ageliinas** [comment]
Bonjour,

J'avais omis de mettre les parenthèses dans les v-if. Je les ai ajouter et maintenant les validations sont de retour. MAIS une fois déposé en ligne, la même erreur se répète avec le champ qui se vide tout de même rendu à la validation.

Voici comment il est écrit dans la method. Aucun des computed ne l'utilise non plus (si jamais)
```
nbJoursRetraite:
        code: |
          (){
              return this.obtenirNbJoursEntreDeuxDates(new Date(), this.dateRetraite)
          }
```

**Comment by j0ber** [comment]
Quel est le nom de votre formulaire en ligne je vais aller voir?
Merci

**Comment by ageliinas** [comment]
Ça semble fonctionner!
Merci

**Comment by j0ber** [comment]
Parfait! Au moins ça fonctionne en attendant notre correctif sur l'évaluation côté serveur des computed, et c'est plus simple que la solution de contournement qui implique un champ hidden et une watch.

Cela dit votre utilisation des computed était adéquate pour votre besoin. Vous pourrez les remettre une fois le bug corrigé.

L'issue reste donc ouvert en attendant le correctif.

Bonne journée!

**Comment by j0ber** [comment]
Le problème a été corrigé. Nous avons oublié de faire un suivi.
