### ISSUE TITLE
Impossible d'utiliser la syntaxe mustache à plus d'un niveau sous l'objet DonneesFormulaire

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#147]
_Originally posted by @anisite in https://github.com/MTESSDev/FRW/discussions/136#discussioncomment-7168728_

AB#65003

**Comment by anisite** [comment]
@loima02 C'est prêt en master, valider qu'on as rien d'autre dans le tuyau et livrer ASAP en IT SVP 👯

**Comment by loima02** [comment]
C'est en PROD!
