### ISSUE TITLE
Bloc adresse - adresses hors Québec et hors Canada

### ISSUE THREAD

**Issue by florentarneodo** [MTESSDev/FRW#149]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
1/ Votre bloc adresse ne gère pas les adresses hors Québec et hors Canada.
2/ Est-il possible de valider que l'adresse au Canada existe vraiment, Poste Canada offre ce service

**Décrivez votre besoin**
On a de la clientèle ou des conjoints qui habitent à l'étranger dont il faut leur adresse.

**Décrivez les alternatives que vous avez envisagées**
Notre plan B est de créer les champs un à un, mais on perd le lien avec Poste Canada sur l'exactitude d'une adresse.

**Proposition de solution**
Commencer par demander le pays et selon le choix, laisser les champs libres de contrainte pour les pays hors Canada avec 2 lignes d'adresse; pour le Canada, ça peut être semblable, mettre la notion de province, valider que l'adresse existe

**Contexte supplémentaire**
N/A

[AB#74094](https://devops700.itp.extra/700/TPM/_workitems/edit/74094)

**Comment by florentarneodo** [comment]
Notre collègue UX peut vous accompagner si vous voulez pour l'ordre des questions, disposition, etc. :
Bolduc Marie-Josée <marie-josee.bolduc@retraitequebec.gouv.qc.ca>

**Comment by ageliinas** [comment]
Pour ajouter à la demande de Florent @florentarneodo , **Voici les commentaires de Marie-Josée Bolduc** [marie-josee.bolduc@retraitequebec.gouv.qc.ca](mailto:marie-josee.bolduc@retraitequebec.gouv.qc.ca) concernant les corrections à apporter du bloc Adresse

**Voici nos besoins pour le bloc adresser :**
- Permettre la saisie d’adresse hors Québec (ex : une adresse à Ottawa)
- Permettre la saisie d’adresse hors Canada (ex : une adresse d’Europe)

**Pour répondre à ce besoin,** 
-  le libellé « province » ne s’applique pas à tous les pays. Dans nos autres services en ligne nous l’avons libellé « Province, territoire ou État »
- Ajouter le Pays : Nous devons permettre à quelqu’un hors Canada d’inscrire une adresse.
- La case postale ne s’appelle pas de cette façon dans tout les pays, est-ce que le lien « Je dispose d’un adresse avec case postale » pourrait être paramétrable pour que nous puissions le désactiver dans certaines situations ?
- Si l’assistant à la saisie n’est pas possible pour les adresses hors Canada, il faudrait que l’option « Saisir l’adresse manuellement » soit offert dès le départ et non à la suite d’une recherche d’adresse infructueuse.

**Autres points :** 
- Si la personne modifie son adresse après avoir obtenu la zone de vérification verte « adresse complète », il faudrait que cette zone se retire, puisque l’adresse n’est plus vérifiée.
- Puisque pour compléter la demande, l’utilisateur est obligé de faire « Rechercher » sinon son adresse n’est pas reconnue, valide par le formulaire même si elle l’est. **Il faudrait permettre d’ajouter une indication sous le libellé « Adresse »** ex : Vous devez inscrire le numéro et le code postal, ensuite cliquez sur le bouton « rechercher » afin de valider l’adresse.

Merci!

**Comment by j0ber** [comment]
Exemple d'un formulaire contenant un champ adresse "international" avec Poste Canada :

https://services.retraitequebec.gouv.qc.ca/CNWI411_PrEnvoiNumerique/fr-CA/EnvoiNumerique/Renseignements

**Comment by j0ber** [comment]
> Pour la RBQ - Nous avons aussi le besoin de rechercher des adresses hors Québec avec le code postal. Idéalement le module de Poste Canada serait utilisé. Nous avons aussi le besoin de saisir des adresses hors Canada.

Une première version du contrôle d'adresse internationale est disponible ici: https://demo-formulaires.it.mtess.gouv.qc.ca/fr/7?s=79A41575-BF7C-45CA-992E-957B62F19994  (Utiliser le formulaire nommé "TEST-001 - Test du composant "Adresse internationale"). Ce n'est pas la version finale, mais vous pouvez l'essayer et faire vos commentaires.

**Comment by jpbeaulieu1** [comment]
> Une première version du contrôle d'adresse internationale est disponible ici: https://demo-formulaires.it.mtess.gouv.qc.ca/fr/7?s=79A41575-BF7C-45CA-992E-957B62F19994 (Utiliser le formulaire nommé "TEST-001 - Test du composant "Adresse internationale"). Ce n'est pas la version finale, mais vous pouvez l'essayer et faire vos commentaires.

Merci pour la réponse rapide! Serait-il d'avoir les particules d'adresses comme pour l'autre composant?
"Rue": "RUE JACQUES-PARIZEAU",
"NoCivique": "425",

**Comment by j0ber** [comment]
En fait si l'adresse est résolue avec postes canada, vous aurez accès à tout ce qui est retourné par poste canada, i.e. une adresse entièrement décortiquée (dans le champ "AdressePostesCanada" du modèle de données si vous activez le paramètre "conserver-donnees-postes-canada").

Voir exemple 2  à la page "Avec postes Canada", et regarder le contenu du champ "AdressePostesCanada" dans le modèle de données.

Si l'adresse n'est pas résolue avec postes Canada, on utilise les champs d'adresse standards tels qu'ils sont actuellement définis.  Comme c'est international utiliser des champs trop précis devient difficile. C'est différent d'un pays à l'autre.

**Comment by jpbeaulieu1** [comment]
Parfait!
Chaque fois que "ModeSaisie": "postes-canada" on ira récupérer les particules dans "AdressePostesCanada" 
Merci

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
