### ISSUE TITLE
Générer un PDF pour impression sur la page de confirmation  

### ISSUE THREAD

**Issue by NOzarenschi** [MTESSDev/FRW#153]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
La fiche de dépistage (formulaire 6478-03) est remplie et envoyée au BSQ de proximité par les ressources externes par télécopieur, ce qui est un irritant majeur. Un envoi automatique du formulaire via FRW vers le BSQ de proximité est prévu dans le futur.

**Décrivez votre besoin**
La ressource externe a besoin de conserver le PDF de sa demande (sans la recevoir par courriel) et l’imprimer.

**Décrivez les alternatives que vous avez envisagées**
Un envoi automatique du formulaire, une fois rempli, à la ressource externe par courriel via FRW (en enlevant certains champs contenant des renseignements personnels) a été envisagé. Nous ne pouvons pas aller de l’avant avec cette solution, car il y a des enjeux en lien avec la protection des renseignements personnels lors de l'envoi par courriel.

**Proposition de solution**
Afficher un bouton « Imprimer » à côté de celui « Soumettre » (ou à un autre endroit jugé pertinent), pour que la ressource externe puisse imprimer la copie PDF du formulaire qu’elle vient de remplir.  

**Contexte supplémentaire**
Un échange de courriels a eu lieu à ce sujet entre Nathalie Beaulieu (Coordonnatrice de l’équipe des communications administratives) et Yanick Fortier le 20 octobre dernier. 

[AB#72848](https://devops700.itp.extra/700/TPM/_workitems/edit/72848)

**Comment by LarcM7** [comment]
Bonjour, merci pour la demande de fonctionnalité.

L'équipe travaille actuellement sur des travaux prioritaires, ce qui fait que l'évaluation de votre demande ne pourra être faite à très court terme. 

Toutefois, elle sera évaluée et priorisée dès que possible, et nous vous tiendrons informé.

Merci et bonne journée

**Comment by loima02** [comment]
C'est en PROD!
