### ISSUE TITLE
Validations min et max

### ISSUE THREAD

**Issue by LarcM7** [MTESSDev/FRW#158]
**Description du problème**
Les validations min et max ne se comportement plus correctement.

**Étapes pour reproduire le bogue**
1. Mettre une validation min ou max sur un contrôle
2. Selon le contrôle, le comportement peut varier, mais est problématique dans tous les cas sauf pour un contrôle "customFile"

**Comportement attendu**
Que les validations min et max se comportement correctement.

[AB#73340](https://devops700.itp.extra/700/TPM/_workitems/edit/73340)

**Comment by LarcM7** [comment]
Note : permettra de remettre la validation `max: 7` sur la liste des types de document dans le formulaire de Dépôt manuel de la GED

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
