### ISSUE TITLE
Ajouter une option à la tâche traiterDocumentsSoumis pour désactiver l'estampillage des pièces jointes

### ISSUE THREAD

**Issue by LarcM7** [MTESSDev/FRW#159]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
L'option de ne pas avoir d'estampille sur une pièce jointe n'existe pas. Cela fait en sorte que l'estampille est toujours présente. 

**Décrivez votre besoin**
Certains systèmes autorisés veulent estampiller les documents avec la date de réception. Or, l'estampille ajoutée par FRW affiche la date de transmission. Cela pourrait créer de la confusion.

**Propostion de solution**
Ajouter une option dans le fichier de configuration de transmission afin de pouvoir désactiver l'estampillage automatique des pièces jointes. Exemple : desactiverEstampille 

AB#69011

**Comment by anisite** [comment]
Livré
