### ISSUE TITLE
Problème de rafraichissement du contenu d'une liste déroulante (Non multiple) ou bouton radio

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#163]
J'ai un problème de rafraichissement du contenu d'une liste déroulante (Non multiple) ou bouton radio

1 - Je saisi un champ 1 qui influence les choix possibles d'un champ 2
2 - Je saisi le champ 2 (type select simple) et des champs conditionnels s'affichent
3 - Je modifie le champ 1 qui modifie les choix possibles du champ 2
4 - Les champs conditionnels devraient se cacher car le champ 2 n'a pas été encore rechoisi
 
P.S. Si le champ 2 est un select multiple, ça fonctionne normalement.

J'ai montré le problème à Christian

[AB#73338](https://devops700.itp.extra/700/TPM/_workitems/edit/73338)

**Comment by j0ber** [comment]
c'est en prod

**Comment by drogu02** [comment]
Bonjour, je viens de tester, et le problème est toujours présent.

**Comment by j0ber** [comment]
En effet le problème est réglé pour les champs avec valeur multiple, mais pas unique... Je regarde ça.

**Comment by j0ber** [comment]
Tout est  réglé et c'est en PROD
