### ISSUE TITLE
Mots-clés ou Libellés NULL dans un domaine font planter l'ouverture d'un formulaire

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#164]
**Description du problème**
Le null est non géré dans une pré-remplissage d'un domaine de valeur.

**Étapes pour reproduire le bogue**
1. Passer null comme contenu

**Comportement attendu**
Devrait être ignoré et laissé vide pour les mots clés et afficher le nom de la clée pour un label sans texte.

**Captures écran**

**Appareil utilisé/fureteur utilisé**

**Autres informations**

AB#71003

**Comment by vinnyboii** [comment]
livré avec le milestone 2023.12
