### ISSUE TITLE
Option value au lieu du label envoyé dans le fichier généré

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#165]
Lorsque j'ai une liste déroulante de type listeDeroulante dans laquelle les options sont ajoutées par un domaine de valeur, je reçois la valeur de l'option au lieu du libellé de l'option dans le fichier fichier généré.

Quand c'est une liste déroulante de type listeDeroulante avec les options ajoutés directement dans le champ, ça fonctionne bien.

![image](https://github.com/MTESSDev/FRW/assets/43148349/bd27b292-eed1-4d59-82a8-2b55e90c748b)

AB#71030

**Comment by anisite** [comment]
Salut est-ce pour OFC et est-ce urgent?

**Comment by drogu02** [comment]
Non ce n'est pas urgent! Non ce n'est pas pour OFC!

**Comment by anisite** [comment]
Après discussions ça été repriorisé, ça monte en IT ce matin

**Comment by vinnyboii** [comment]
livré dans le milestone 2023.12

**Comment by drogu02** [comment]
Ce problème est de retour. Ça ne focntionne pas pour les liste déroulantes qui sont remplis par une liste de valeur.

![image](https://github.com/MTESSDev/FRW/assets/43148349/51168d6c-dfe7-4058-becf-89c54019f4e9)

![image](https://github.com/MTESSDev/FRW/assets/43148349/57c3d2e1-0406-4d95-addc-8980bec46458)
