### ISSUE TITLE
Saisie de numéraux de téléphones internationaux

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/FRW#168]
Nous avons le besoin de saisir un numéro de téléphone à l'international.

par exemple:

![image](https://github.com/MTESSDev/FRW/assets/112179879/124af5d6-d325-4228-af3a-d1015d8f331a)

[AB#73343](https://devops700.itp.extra/700/TPM/_workitems/edit/73343)

**Comment by drogu02** [comment]
J'ai le même besoin pour un formulaire au DEC

**Comment by j0ber** [comment]
Une version très simple a été mise en place afin d'au moins permettre de saisir autre chose qu'un no. de téléphone au format nord  américain, tout en restreignant un peu ce qu'il est possible de saisir (ex. pas de lettre, pas de parenthèses n'importe où, etc.)

Utilisez ce champ lorsque dans les cas précis où vous savez que le numéro de téléphone n'est pas canadien ou américain.

Aucun formatage n'est effectué et la validation est très basique afin qu'un numéro de téléphone de n'importe quel pays puisse être saisi.

Il est disponible ici: https://formulaires.it.mtess.gouv.qc.ca/fr/Form/7/P700U/0/N/#p=sectionTel et peut être utilisé dans vos formulaires.

Nous verrons plus tard s'il vaut la peine d'avoir un plugin permettant une validation plus poussée pour ce contrôle qui risque d'être peu utilisé.
