### ISSUE TITLE
Double signature dans FRW

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#170]
**Décrivez votre besoin**

Nous avons besoin de permettre la complétion et la signature d'un même formulaire par une ou deux parties distinctes.

1. Lorsqu'applicable, la deuxième partie doit être impliquée une fois que la première partie a transmis ses informations.
2. Ce processus doit se faire en mode anonyme puisque le client ne dispose pas d'un système backend pour gérer les appels à FRW.
3. On doit s'assurer que chaque partie puisse modifier seulement l'information qui lui est demandée.

**Proposition de solution**
Voir la solution de double signature en PJ dans la carte Azure devops.

[AB#73277](https://devops700.itp.extra/700/TPM/_workitems/edit/73277)

**Comment by loima02** [comment]
C'est en IT!

**Comment by anisite** [comment]
À noter que la gestion des "computed" du injecterJs est changée pour cette release

**Comment by anisite** [comment]
Dans l'aiguillage la notion d'étapes va être ajoutée pour permettre de réutiliser le même formulaire

**Comment by drogu02** [comment]
Autre petite correction de nécessaire en lien avec le readonly (Si possible)

Pouvoir mettre un groupe répétable en readonly pour enlever les boutons ajouter et supprimer
![image](https://github.com/MTESSDev/FRW/assets/43148349/36d7c50f-6e1b-44fd-bcd2-a936ae4f926b)

Lorsque le champ de tye adresse est en readonly, enlever les boutons Effectuer une nouvelle recherche et Saisir l'adresse manuellement
![image](https://github.com/MTESSDev/FRW/assets/43148349/aee76650-9322-455b-b8ea-cec4b39f2f1d)

**Comment by drogu02** [comment]
De plus empêcher la suppression des fichier ou l'ajout si en readonly
![image](https://github.com/MTESSDev/FRW/assets/43148349/059541cc-de43-49c3-b8fa-69f4db00851e)

**Comment by drogu02** [comment]
Donc, j'aimerais pouvoir mettre ceci :

additionals:
    :readonly: val('etape') == 'premierFormulaireCompleter'

à ces champs :
   
   type: adresse
   type: customfile
   type: repeatableGroup

**Comment by loima02** [comment]
C'est en PROD!

**Comment by drogu02** [comment]
Merci!
