### ISSUE TITLE
options NULL dans une étape du fichier de transmission fait planter le traitement

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#172]
**Description du problème**
Dans une étape d'un fichier de transmission, si on met une options nulle, le traitement de transmission plante.

**Étapes pour reproduire le bogue**
Exemple d'une étape de transmission avec une option nulle qui est en erreur:
  - tache: genererWord
    options:

**Comportement attendu**
Le traitement devrait fonctionner normalement si on a une option nulle.

[AB#73337](https://devops700.itp.extra/700/TPM/_workitems/edit/73337)

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
