### ISSUE TITLE
Intégrer la version 2.0.0 des composants UTD + support NodeJs 20+ MtessVueFormulate

### ISSUE THREAD

**Issue by j0ber** [MTESSDev/FRW#174]
**Décrivez votre besoin**
Intégrer la version 2.0.0. des composants UTD et mise à jour FRW-VueFormulate afin de supporter NodeJs version 20+.

[AB#74095](https://devops700.itp.extra/700/TPM/_workitems/edit/74095)

**Comment by loima02** [comment]
C'est en IT!

**Comment by j0ber** [comment]
C'est en PROD
