### ISSUE TITLE
Champ groupe - Effet visuel désagréable (décalage) lors du focus sur l'entête d'un groupe

### ISSUE THREAD

**Issue by j0ber** [MTESSDev/FRW#176]
**Description du problème**
Lorsque l'entête d'un groupe reçoit le focus, le contenu du groupe décale légèrement.

**Étapes pour reproduire**
1. Aller à dans le P700, dans la section "Contrôles -> Groupes".
2. Faire des Tab jusqu'à ce qu'on arrive sur l'entête d'un groupe
3. Refaire Tab, puis Shift-Tab pour revenir sur l'entête (si on veut reproduire à plusieurs reprises afin de bien voir le problème)

**Comportement attendu**
Le focus sur l'entête du groupe de devrait pas décaler la zone de contenu du groupe.
Voir accordéon UTD pour référence sans décalage.

[AB#73368](https://devops700.itp.extra/700/TPM/_workitems/edit/73368)

**Comment by loima02** [comment]
C'est en IT!
