### ISSUE TITLE
Pouvoir mettre une liste déroulante par ordre alphabétique - FR et EN

### ISSUE THREAD

**Issue by florentarneodo** [MTESSDev/FRW#177]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Il est irritant lorsqu'on fait une liste déroulante par ordre alphabétique FR, la traduction anglaise suit l'ordre alphabétique français et est donc incohérente.

Exemple, la liste anglaise n'est pas par ordre alphabétique
Deux    Two
Trois     Three
Un        One

**Décrivez votre besoin**
Si on souhaite mettre une liste par ordre alphabétique (car elle contient plusieurs dizaines éléments), qu'elle s'affiche en ordre alphabétique en français et en anglais.

**Décrivez les alternatives que vous avez envisagées**
Pas d'idées d'alternative

**Propostion de solution**
Rajouter une option facultative qui permet de dire à la solution de mettre une liste par ordre alphabétique

**Contexte supplémentaire**
Exemples de listes :
- liste de pays
- liste des employeurs

Merci et bonne journée. :)

[AB#74096](https://devops700.itp.extra/700/TPM/_workitems/edit/74096)

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
