### ISSUE TITLE
Passer un paramètre à l'URL lors de l'aiguillage en mode redirectionUrl

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/FRW#178]
**Décrivez votre besoin**
Être en mesure de passer un paramètres dans l'URL vers lequel l'aiguillage renvoie l'utilisateur. Par exemple le numéro de confirmation. Le but étant de pouvoir aiguiller l'utilisateur vers une page spécifique.

**Décrivez les alternatives que vous avez envisagées**
Ajouter  un message dans la page de confirmation de transmission qui explique à l'utilisateur de naviguer vers la page indiquer. C'est moins convivial que la redirection par le système.

**Propostion de solution**
Permettre de passer un paramètres ou une variable dans l'URL

config:
  aiguillage:
    choix:
      - mode: redirectionUrl
        url: http://rbq.gouv.qc.ca/PageDeQuelqueChose/{{NoConfirmation}} 

[AB#73367](https://devops700.itp.extra/700/TPM/_workitems/edit/73367)

**Comment by jpbeaulieu1** [comment]
Je viens de voir la demande 156 est la même chose.

**Comment by anisite** [comment]
Fermé pour faire le suivi sur #156 merci @jpbeaulieu1
