### ISSUE TITLE
Contrôle d'adresse - Ajouter une validation de longueur sur le champ "Appartement ou bureau"

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#180]
**Description du problème**
Selon les normes de design quebec.ca, le champ "Appartement ou bureau" devrait permettre un maximum de 5 caractères.
Le contrôle d'adresse normalisé ne bloque pas ce champ actuellement et cela cause des problèmes dans le système ECS lors de la création GDI.

**Étapes pour reproduire le bogue**
1. Aller dans n'importe quel formulaire qui a un contrôle d'adresse normalisé.
2. Le contrôle d'adresse normalisé n'a aucune validation de longueur sur le champ "Appartement ou bureau"
4. BANG!

**Comportement attendu**
Ajouter une validation de longueur (max 5 caractères) sur le champ "Appartement ou bureau"

**Captures écran**
![image](https://github.com/MTESSDev/FRW/assets/128411313/9af151ca-d0b2-4a07-91c3-930aaed21023)

[AB#74097](https://devops700.itp.extra/700/TPM/_workitems/edit/74097)

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
