### ISSUE TITLE
Url de l'aiguillage inconnu dans le schema du formulaire

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#184]
L'url de l'aiguillage est en rouge dans le formulaire. il doit être ajouté dans le schema du formulaire

![image](https://github.com/MTESSDev/FRW/assets/43148349/3fb38eeb-3b9f-45b3-b86b-34f8f6b7f50a)

[AB#73941](https://devops700.itp.extra/700/TPM/_workitems/edit/73941)

**Comment by anisite** [comment]
Bonsoir, Est-ce que c'était ok avant? Possible que ça ait été accroché récemment quand la story pour avoir une URL multilingue, @Quasar-0 tu pourrais vérifier ça et me revenir, normalement l'ancienne façon d'écrire l'URL sans multilingue devrait continuer de fonctionner après la story en cours.

**Comment by drogu02** [comment]
Je ne sais pas si c'était correct avant, ça ne fait pas très longtemps que j'utilise l'aiguillage.

**Comment by loima02** [comment]
C'est en IT!

**Comment by j0ber** [comment]
C'est en PROD

**Comment by j0ber** [comment]
C'est livré
