### ISSUE TITLE
Passer FRW en .NET8

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#186]
**Décrivez votre besoin**
Intégrer .NET8 dans FRW  

[AB#74074](https://devops700.itp.extra/700/TPM/_workitems/edit/74074)

**Comment by anisite** [comment]
ça va monter avec https://github.com/MTESSDev/FRW/issues/166

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
