### ISSUE TITLE
Bogue avec le module d'adresse internationale

### ISSUE THREAD

**Issue by jodionrq** [MTESSDev/FRW#188]
**Description du problème**
L'intégration du module d'adresse internationale bloc la transmission du formulaire. 

**Étapes pour reproduire le bogue**
1. Aller à : https://formulaires.it.mtess.gouv.qc.ca/240002?s=F995D56C-D659-4FF7-A650-D7A8C3DDAC36
2. Cliquer sur : CRQ-001-001-STA - 1.0.0 - Consentement à la communication de renseignements
3. À la section "Renseignements sur la demande" à la question "À qui voulez-vous donner l'autorisation?", choisir "
Personne (parent, amie ou ami, aidante ou aidant naturel, etc.)"
4. Compléter le formulaire.
5. Rendu à "Transmettre ma demande", en cliquant sur le bouton, ça nous ramène toujours sur la même page.

**Comportement attendu**
Si à la question "À qui voulez-vous donner l'autorisation?", choisir " vous choisissez "Organisme", tout fonctionne, car le module d'adresse internationale n'est pas là. Le demande se transmet et un reçoit une page de confirmation.
J'ai testé le formulaire en désactivant la clé de Postes Canada et ça ne marchait pas non plus. C'est seulement en utilisant le module d'adresse internationale où le bogue de transmission se produit. En cliquant sur "Transmettre ma demande", on revient toujours sur la même page.

**Captures écran**
![image](https://github.com/MTESSDev/FRW/assets/124822406/ecf113f1-e94b-49ec-bd6d-64e70aed490c)

**Appareil utilisé/fureteur utilisé**
 - OS: Windows 10 
 - Fureteur: Edge Version 120.0.2210.144 (Version officielle) (64 bits)

**Autres informations**
- Version de l'application FRW : 2024.2
- Date/heure de l'événement (2024-01-01 9h00)

AB#74161

**Comment by j0ber** [comment]
C'est corrigé, vous pouvez réessayer.

Il semble que nous aillons eut un petit problème de merge de code.
