### ISSUE TITLE
Correction/Amélioration du readonly et disabled sur certains champs ou groupe

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#190]
J'aimerais pouvoir mettre en readonly et disabled certains champs lorsque l'on est rendu dans l'étape 2 (signature) d'un formulaire.

Donc, j'aimerais pouvoir mettre ceci :

additionals:
    :readonly: val('etape') == 'premierFormulaireCompleter'

à ces champs :
   
   type: adresse
   type: customfile
   type: repeatableGroup

Pouvoir mettre un groupe répétable en readonly et disabled pour enlever les boutons ajouter et supprimer
![image](https://github.com/MTESSDev/FRW/assets/43148349/a31cfc47-980b-44ff-a92a-2c6608a61645)

Lorsque le champ de type adresse est en readonly et disabled, enlever les boutons Effectuer une nouvelle recherche et Saisir l'adresse manuellement
![image](https://github.com/MTESSDev/FRW/assets/43148349/28b14fbc-ef15-462c-a8a6-141299a218a8)

empêcher la suppression des fichiers ou l'ajout si en readonly et disabled
![image](https://github.com/MTESSDev/FRW/assets/43148349/5622cbe9-c1cb-45fc-bd08-0d9fd5803999)

Ce besoin serait requis dans la livraison des formulaires du MTRAV pour le 31 mars.

Merci

[AB#74791](https://devops700.itp.extra/700/TPM/_workitems/edit/74791)

**Comment by loima02** [comment]
C'est en IT!

**Comment by drogu02** [comment]
Ce n'est pas fonctionnel en IT.

**Comment by LarcM7** [comment]
Bonjour, 

De mon côté après vérification je confirme que ça fonctionne en IT.

Il doit y avoir autre chose. 

disabled et/ou readonly sur repeatableGroup, adresse ou adresseInternationale et customfile.

Pouvez-vous décrire votre test et le résultat obtenu? 

Merci

**Comment by j0ber** [comment]
C'est réglé maintenant et c'est en IT
