### ISSUE TITLE
Un champ de type adresse dans un groupe répétable empêche la soumission du formulaire

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#191]
Un champ de type adresse dans un groupe répétable empêche la soumission du formulaire mais on voit aucune erreur à l'affichage.

Vincent m'a envoyé l'erreur qu'il voit en arrière :

    "status": 400,     "errors": {       "adresseArbitre.0.Province": [         "The Province field is required."       ],       "adresseArbitre.0.Municipalite": [         "The Municipalite field is required."

[AB#75018](https://devops700.itp.extra/700/TPM/_workitems/edit/75018)

**Comment by anisite** [comment]
Bonjour,
les groupes dans des groupes ne sont pas supportés, le type adresse est basé sur le type groupe derrière puisqu'il regroupe plusieurs champs en un seul, l'interface du bac à Sable aurait probablement dû prévenir l'utilisation du champ dès le départ, désolé de la situation.

**Comment by drogu02** [comment]
Ha ok!  Pas de problème! Je vais y aller autrement, merci!
