### ISSUE TITLE
FRW: Ajouter TypeFormulaire dans le JSON de transmission

### ISSUE THREAD

**Issue by Greju01** [MTESSDev/FRW#194]
AJouter le type de formulaire pour SGD

[AB#75165](https://devops700.itp.extra/700/TPM/_workitems/edit/75165)

**Comment by anisite** [comment]
Sera monté en IT ce matin, en prod c'est planifié pour le 12 mars 2024

**Comment by loima02** [comment]
C'est en PROD!
