### ISSUE TITLE
Option value au lieu du label envoyé dans le fichier généré

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#195]
Ce problème est de retour. Ça ne fonctionne pas pour les liste déroulantes qui sont remplis par une liste de valeur.
https://github.com/MTESSDev/FRW/issues/165

Ça me faite ça avec ce formulaire en IT et en Prod
MTRAV-Formulaires

[AB#75182](https://devops700.itp.extra/700/TPM/_workitems/edit/75182)

**Comment by anisite** [comment]
Un fix a été monté en IT et en PROD. SVP nous revenir pour nous informer des résultats.

**Comment by drogu02** [comment]
C'est parfait, ça fonctionne merci!
