### ISSUE TITLE
Problème mineur avec le min à 0 dans le champ de type number

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#196]
Quand je met 1 dans le min, je ne peux pas descendre en bas de 1 avec les flèches du champ, et c'est parfait! 

Par contre, quand je met min à 0, c'est possible de descendre dans le négatif avec le champ.

![image](https://github.com/MTESSDev/FRW/assets/43148349/63efbd5d-03a3-411d-a103-28d8f6a5900e)

![image](https://github.com/MTESSDev/FRW/assets/43148349/f86ce7d9-5d85-4d13-af39-158112282732)

[AB#75185](https://devops700.itp.extra/700/TPM/_workitems/edit/75185)

**Comment by anisite** [comment]
est-ce que ça vaut la peine de corriger ça en même temps que https://github.com/MTESSDev/FRW/issues/158 ?

**Comment by j0ber** [comment]
> est-ce que ça vaut la peine de corriger ça en même temps que #158 ?

Oui. Après vérification le problème est backend. Il semble que lorsque "min" a la valeur 0, l'attribut "min" n'est pas rendu dans le html. @anisite tu as mentionné que ça pouvait être lié à Stubble.

**Comment by drogu02** [comment]
Mon client vient de me mentionner qu'il est aussi capable d'inscrire un -0 dans un champs de type number. 

Inscrire -0 ne devrait pas être possible et/ou automatiquement transformé à 0.

**Comment by anisite** [comment]
@drogu02  le champ c'est un type number natif, c'est le comportement du navigateur, et 0 c'est un chiffre spécial il est ni négatif ni positif donc il est valide autant avec un - que sans.

il ne semble donc pas y avoir de bug avec le comportement soulevé
