### ISSUE TITLE
Formulaire de Finalisation de la demande - Bouton Suivant et format d'affichage

### ISSUE THREAD

**Issue by LudovicD-Mess** [MTESSDev/FRW#198]
Il est irritant d'avoir des champs et bouton qui ne servent pas dans la validation d'un formulaire.

Description du besoin : 
Dans l'écran de 'Finalisation de la demande' : 

1. Le bouton Suivant est inactif. Il ne sert a rien ici.
2. Le texte ''* Réponse obligatoire'' ne sert a rien non plus il n'y a rien a saisir.
3. Le texte '[Vérification des erreurs]' Indique une valeur 1 alors qu'il n'y a pas d'erreur.

Alternative et proposition de solution : 

1. Reordonner les boutons pour avoir precedent et soumettre sur la même ligne (sans le bouton suivant donc)
2. Supprimer le texte Réponse obligatoire 
3. Ne pas indiquer une valeur a coté de 'Vérification des erreurs'

[AB#75337](https://devops700.itp.extra/700/TPM/_workitems/edit/75337)

**Comment by j0ber** [comment]
Bonjour,

Avez-vous une impression d'écran pour votre point 3? Je ne comprend pas de quoi vous parlez.
Merci!

**Comment by LudovicD-Mess** [comment]
![image](https://github.com/MTESSDev/FRW/assets/160150555/44640038-c888-4d7b-b362-808a890995f2)
Voici la capture d'image

**Comment by j0ber** [comment]
Pour votre point 3, "Vérification des erreurs" c'est le nom que VOUS avez donné à l'étape... Généralement nous l'appelons "Révision". Le 1 c'est le no de la section dans le groupe de sections "Finalisation de la demande".
Nous ne changeons pas ça. Cette étape de vérification pourrait être la 5ème.... Toutes les étapes (sections) sont numérotées.

Vous pouvez aussi bâtir un formulaire sans groupe de sections.  Exemple :

```sectionsGroup:
    - sections:
        - section: 
            fr: Informations sur la demande
            en: Information on the application
          id: infos
          components:   
             ...
        - section: 
            fr: Une deuxième section
            en: (en)Une deuxième section
          id: section2
          components:   
             ...
        - section: 
            fr: Une troisième section
            en: (en)Une troisième section
          id: section3
          components:   
             ...

**Comment by j0ber** [comment]
Concernant votre point 2. 
Vous avez probablement retiré le paramètre "**cacherTexteExplicatifChampsObligatoires**". 
Ce dernier permet justement de ne pas afficher le texte explicatifs pour les champs obligatoires. Il peut être utilisé dans l'importe quelle page (ex. certainement la page de révision, ou encore une page qui ne contiendrait que du texte, donc aucun champ)

```
        - section: 
            fr: Révision
            en: Revision
          id: revision
          cacherTexteExplicatifChampsObligatoires: true          
          components:

**Comment by j0ber** [comment]
Pour votre point 1, le fait que le bouton soit désactivé n'est pas un problème.  Précédent et soumettre ne seront jamais sur la même ligne... 

Les boutons en bas de la page sont pour la navigation et l'enregistrement... La validation et la soumission ne doivent pas se retrouver là.

Nous ne changerons pas cela.

Cependant il avait déjà été discuté de revoir la façon dont nous affichons les boutons de navigation. Il se peut donc que ça change un jour. Cependant le bouton "Soumettre" ne sera jamais avec la navigation.
