### ISSUE TITLE
Anomalie liste de format de fichier accepté

### ISSUE THREAD

**Issue by MJMESS** [MTESSDev/FRW#2]
Les formats de fichier acceptés fonctionnent dans le bac à sable mais lorsque le formulaire est généré à l'aide du client, il accepte seulement le premier format qui est inscrit dans l'attribut mime et ignore les autres.

Dans le bac à sable, ça fonctionne, j'ai l'erreur du format uniquement lorsque j'essais de télécharger un format de fichier qui n'a pas été défini dans le mime.

Mais dans le formulaire générer avec le client il accepte que le premier qu'il y a dans la liste de mime, les autres formats inclus dans la liste sont ignorés et nous affiche l'erreur que le format n'est pas accepté.

Merci

**Comment by anisite** [comment]
bonjour, est-ce possible de nous copier le bloc de config du champ en erreur SVP ?

**Comment by MJMESS** [comment]
- name: PieceJointe
                  type: customfile
                  label:
                    fr: Joindre le fichier
                  help: 
                    fr: Sélectionner des fichiers de type images (JPEG, GIF ou PNG), de documents Microsoft Word, Excel ou PowerPoint, de PDF ou de fichiers texte.
                  additionals:
                    multiple: true
                  validations:
                    mime: application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/pdf,application/msword,image/jpeg,image/png,image/gif,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/mspowerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation,text/plain,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

**Comment by anisite** [comment]
nous allons devoir ajuster la documentation, ce ne sont pas tous les types qui sont supportés (par sécurité) il y a :
jpg, png mais pas les gif, et les document docx et xlsx mais pas doc et xls (trop dangereux) il y a aussi les pdf.

ça "fonctionne" dans le bac à sable parce que c'est seulement le côté clien qui valide avec votre liste, arrivé sur le serveur la protection avancée s'assure que personne passe à côté avec des types non supportés (nous devons ajouter la signature de chaques type pour la vérification serveur et non pas seulement valider le mime type)

quels types sont ABSOLUEMENT nécessaires pour votre solution ?

**Comment by anisite** [comment]
@yjobin @j0ber Est-ce que vous pourriez lister les mime types supportés dans le P700u?

**Comment by MJMESS** [comment]
Nous créons des formulaires pour un autre partenaire, dès que j'ai leur réponse, je vous reviens afin de répondre à votre question : quels types sont ABSOLUEMENT nécessaires pour votre solution ?

Merci

**Comment by MJMESS** [comment]
Je n'ai pas encore de nouvelle du partenaire mais j'ai fait quelques essais et même si je mets que les formats que vous acceptez actuellement ou aucune validation afin de prendre les formats par défaut que vous offrez, cela nous donnes des erreurs "Le format du fichier n'est pas accepté". Que doit-on mettre pour que les formats que vous acceptez actuellement passe tous ? 

merci

**Comment by MJMESS** [comment]
Bonjour, parmi les formats que vous dites accepter, le format xlsx ne passe pas, nous avons l'erreur "Le format du fichier n'est pas accepté.

Merci

**Comment by anisite** [comment]
voici la liste des type supportée actuellement (celle par défaut si le paramètre n'est pas précisé)
mime: "image/jpeg,image/png,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.oasis.opendocument.text"

**Comment by anisite** [comment]
Liste complète : 
image/pjpeg
image/jpeg
application/vnd.openxmlformats-officedocument.wordprocessingml.document
application/vnd.oasis.opendocument.text
application/pdf
image/png
image/tiff
image/x-tiff
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

**Comment by MJMESS** [comment]
Merci, oui le fichier a bien été enregistrer en format xlsx. Je viens encore de faire le test avec un nouveau fichier Excel créé et enregistré en format xlsx et j'ai toujours l'erreur du format.

**Comment by anisite** [comment]
si vous renommez le fichier en .zip et que vous l'ouvrez avec l'explorateur ça ressemble à ceci ? 
![image](https://user-images.githubusercontent.com/3194288/213528545-23c51475-5a53-4a4a-abd7-ef74f322b1cf.png)

Sinon, si le fichier n'est pas trop sensible, vous pouvez le faire parvenir à l'équipe FRW ? On pourra le tester.

**Comment by MJMESS** [comment]
Allo,

J'ai la même chose. Le fichier en pièce jointe. Rien de sensible un nouveau fichier pour test.

***@***.***

Merci,

De : anisite ***@***.***>
Envoyé : 19 janvier 2023 13:24
À : MTESSDev/FRW ***@***.***>
Cc : Hamel, Marie-Josée ***@***.***>; Author ***@***.***>
Objet : [EXTERNE] Re: [MTESSDev/FRW] Anomalie liste de format de fichier accepté (Issue #2)

*ATTENTION : Ce courriel provient de l'extérieur de votre organisation.
Évitez de cliquer sur un hyperlien, d'ouvrir une pièce jointe ou de transmettre des informations personnelles si vous ne connaissez pas l'expéditeur du courriel. En cas de doute, communiquez verbalement avec lui.

si vous renommez le fichier en .zip et que vous l'ouvrez avec l'explorateur ça ressemble à ceci ?
[image]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F3194288%2F213528545-23c51475-5a53-4a4a-abd7-ef74f322b1cf.png&data=05%7C01%7Cmarie-josee.hamel%40mtess.gouv.qc.ca%7Cccab51aaae6d43c0208608dafa4a63ad%7C0331467c063c49d0bdba898ee71533e6%7C0%7C0%7C638097494653791250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iBZpg%2FU7UAiUIpQpzss5xtdUokSun7I76o475mPcFpU%3D&reserved=0>

Sinon, si le fichier n'est pas trop sensible, vous pouvez le faire parvenir à l'équipe FRW ? On pourra le tester.

-
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMTESSDev%2FFRW%2Fissues%2F2%23issuecomment-1397422709&data=05%7C01%7Cmarie-josee.hamel%40mtess.gouv.qc.ca%7Cccab51aaae6d43c0208608dafa4a63ad%7C0331467c063c49d0bdba898ee71533e6%7C0%7C0%7C638097494653791250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Shdbwsp6XY%2B6p3vDFhewyPu6zy%2B9UnbXWV5KmgdvR68%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA5G4C5553KTRV6VS4DQCV23WTGBFDANCNFSM6AAAAAATZHYEGE&data=05%7C01%7Cmarie-josee.hamel%40mtess.gouv.qc.ca%7Cccab51aaae6d43c0208608dafa4a63ad%7C0331467c063c49d0bdba898ee71533e6%7C0%7C0%7C638097494653791250%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=e8ofBZB8KCEkWtCHWriGdu%2BLsXJyyWIDmsLo5z45XKQ%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________
Ce message est confidentiel et est à l'usage exclusif du destinataire nommé ci-dessus. Si vous recevez ce message par erreur, sachez qu'il est interdit de le diffuser, de le distribuer, d'en dévoiler le contenu ou de le reproduire. Veuillez informer immédiatement l'expéditeur par courrier électronique et détruire l'original de ce message ainsi que toute copie.
________________________________

**Comment by anisite** [comment]
Ok je vais faire vérifier celà car nous avons une équipe qui l'utilisent normalement....

**Comment by MpmMtess** [comment]
Question sur la façon de spécifier les types de fichiers acceptés (mime). 

Est-ce que lorsque ce sont plusieurs types de format acceptés on doit les spécifier entre guillemets ("") ou pas? 

Ex.:  name: FichiersAAjouterPlusieursFormat
              type: customfile
              label:
                fr: Ajouter un fichier (Format variable)
                en: (EN)Ajouter un fichier
              help:
                fr: ""
              validations:               
                mime: "image/jpeg,image/png,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.openxmlformats-officedocument.presentationml.presentation,application/pdf"

**Comment by anisite** [comment]
> Est-ce que lorsque ce sont plusieurs types de format acceptés on doit les spécifier entre guillemets ("") ou pas?

Il faut savoir que FRW utilise le format YAML et ce n'est pas FRW qui détermine le format, donc tant que le standard YAML est suivi tout est beau.

Donc pour votre question il est possible de l'écrire avec ou sans "" et il serait aussi possible avec '' et même en multiligne au besoin, il y a des cheat sheet comme celles-ci qui peuvent être utiles : https://lzone.de/cheat-sheet/YAML 

la seule limitation c'est sur les strings qui débutent par un caractère réservé "YAML" comme les !, <, >, & et { à ce moment là il est obligatoire de mettre entre "" ou '' ou multilignes.

**Comment by j0ber** [comment]
@MJMESS pouvez-vous me dire où vous en êtes ?  Est-ce que vous avez toujours des problèmes? Si oui, s.v.p. m'indiquer le problème qui est toujours d'actualité (le format xlsx non accepté?, seulement le 1er format accepté? ou autre) Je vais regarder ça si c'est toujours d'actualité.

**Comment by MpmMtess** [comment]
@j0ber ça fonctionne merci!
