### ISSUE TITLE
Personnalisation libellé "votre numéro de confirmation est le xxx"

### ISSUE THREAD

**Issue by florentarneodo** [MTESSDev/FRW#202]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Le libellé "numéro de confirmation" à la toute fin porte à confusion pour le client. On pourrait croire que sa demande est confirmée alors que c'est juste la transmission.

**Décrivez votre besoin**
Pouvoir changer le libellé pour un des choix suivants par exemple :
- Votre numéro de confirmation de transmission est le xxxx
- Votre numéro de transmission est le xxx

**Décrivez les alternatives que vous avez envisagées**
Ajouter une phrase en dessous pour expliquer c'est quoi le numéro de confirmation (information jugée inutile pour l'expérience client). Ça peut rester ambigu

**Proposition de solution**
Rendre personnalisable le libellé "votre numéro de confirmation est le xxx"

**Contexte supplémentaire**
Ajoutez ici tout autre contexte ou capture d'écran concernant la demande de fonctionnalité.

![image](https://github.com/MTESSDev/FRW/assets/140817361/4c47b5fd-f888-4866-b9e3-e2083deebe07)

[AB#76460](https://devops700.itp.extra/700/TPM/_workitems/edit/76460)

**Comment by vinnyboii** [comment]
Bonjour,

Dans un soucis d'uniformité de la solution, nous ne voulons pas permettre de personnaliser ce texte.

Cependant, nous pourrions le modifier pour "Votre numéro de confirmation de transmission est le xxxx" tel que proposé.

Ce sera fait dans une livraison future.

Restez à l'affût.

**Comment by florentarneodo** [comment]
Bonjour,
Nous sommes à la veille de faire notre documentation, est-ce que le changement sera fait d'ici fin mai? ou quand?
Merci et bonne journée.

**Comment by Ghost3044** [comment]
Bonjour, 
Le changement sera effectivement fait pour la fin du mois de mai. Le libellé sera modifié pour : "Votre numéro de confirmation de transmission est le xxx".
Bonne journée

**Comment by j0ber** [comment]
C'est en IT.
![image](https://github.com/MTESSDev/FRW/assets/26974817/02986fd2-9dc5-473b-9125-e6f218782e09)

**Comment by florentarneodo** [comment]
merci!
