### ISSUE TITLE
Bouton "Ajouter des fichiers" n'affiche pas la pièce jointe

### ISSUE THREAD

**Issue by jodionrq** [MTESSDev/FRW#205]
**Description du problème**
On a un bogue avec le bouton "Ajouter des fichiers" depuis hier et ça touche tous nos formulaires. Lorsqu'on ajoute un fichier, le bouton devient pâle, mais on ne voit plus le fichier qui a été ajouté.

**Étapes pour reproduire le bogue**
Aller dans le P700U à la section "Pièce jointes"
https://formulaires.it.mtess.gouv.qc.ca/fr/Form/7/P700U/0/OrM1KsLrlkC6a_oLn6kMzw?utm_source=debuterFormulaire#p=18

**Comportement attendu**
On devrait voir qu'un fichier a été ajouté

**Captures écran**
<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAvQAAACUCAYAAAD8t71lAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAA+OSURBVHhe7d1/jBflnQfwj6UWSm8REN29cnpQSrtVG/wRRVtN15gGui0BrFUo1UI8ldA0QHOemsaqMS16Ji2Gk6ocgWoIbM+rEHorpOG6rXD8uIhworfetrIHYlnwCsJJQW/rzXy/A+wuAgsuxmd9vZJv5pl5ZmfmGf55P8Nnvt/T3slEp22KGcMXxpClP4zrzy5veX7WN+IfBj8Sc7+Wbdg4N4bcuqzc0c7IeGrtzRFt9+1g5y+/H5dvHh+//+4FxZZMfrz5A2PNT0bGWTuWxc2j5kZD0XXYZ2JGfj1n7o6G2ffG9F9G1Nx4XXzna1fGp/sWuwAAQDf1kWLZdb5wc6xZ+0/x+3afm+Oiovu9yScGHY9dTC569I2a786M5+umxuh4NqaPuSXuathR/jMAAOimujbQn3l2XPT8y/G7t4r1Dioqz47Vm08yZPftF+d8/IXY9GqxfjR9B0fNt+6KpT+9KlYvWR87i80AANAddW2g/6ur4par1sa9s1bGztZi21u743ev7i41P10zKq7453+MRzaW16P17di6o2gfz8eGx/WT3owZM38RL+0ttuV/37wjDmTNA394Nbb+qbw5t/Wll2NH/7+InvlK89KYckf2d0eZaAAAQKq6uOSmb4y49+/jro89E6Ou+UYMGf6NuOjGH8UjL/1vufvskTF77sjY+ci0OC/rG3LNLTG9YVe5rxPO+9bMWHDFy/GD68rHPm/MtJjxmyLQ7/jXmDHxm6XtQ4Z/M/5m3QWxYNqV0Sfv+59XY/WGV2JHviMAAHQjJ/hSLAAA8EHS9S/FAgAA7xuBHgAAEibQAwBAwgR6AABImEAPAAAJE+gBACBhAj0AACTshL6Hfs+egz/RCgAAnGp9+lQUraPzhB4AABIm0AMAQMIEegAASJhADwAACRPoAQAgYQI9AAAkTKAHAICECfQAAJAwgR4AABIm0AMAQMIEegAASJhADwAACRPoAQAgYQI9AAAkTKAHAICECfQAAJAwgR4AABIm0AMAQMIEegAASJhADwAACRPoAQAgYQI9AAAkTKAHAICECfQAAJAwgR4AABIm0AMAQMIEegAASJhADwAACRPoAQAgYQI9AAAkTKAHAICECfQAAJAwgR4AABIm0AMAQMIEegAASJhADwAACRPoAQAgYQI9AAAkTKAHAICECfQAAJAwgR4AABIm0AMAQMIEegAASJhADwAACRPoAQAgYQI9AAAkTKAHAICECfQAAJAwgR4AABIm0AMAQMIEegAASJhADwAACRPoAQAgYQI9AAAkTKAHAICEnfZOpmgf1549e4vWyam6dUHRgu5h++MTihYAQNfr06eiaB3d+x7o9y2aXKxB2nqPe1SgBwBOqc4EeiU3AACQMIEeAAASJtADAEDCBHoAAEiYQA8AAAkT6AEAIGECPQAAJEygBwCAhAn0AACQMIEeAAASJtADAEDCBPpU7VwZ48c9Gr3nNhYbTqE3m+Kx++fEefn5ss/VczbG/qKr097P6wUA+BBJNtC/8WxdKVz2vnFprG0tNh5yINY+mvctiCU7i02cpAPRMH9FTH+xNT5bc0EsnDg0vn3pubG9/okYPG5ePNxU7NZVXsuC/43ZpGF+04lPGgAAPoQSDfS7ouG3uyJOj6h8e1ssW3+g2H5Yr149i9ap80ZDNqm4e2W0FOvd02uxcUO2qBgc906+MkaPvCYmXtiv3JXd/17lVtc5vUfXHxMAoBtLM9DvborlL0QM+/LgmJyFyvnrGjs8ze0ZwyZOin1PTojRZxWbutzeWLMmm1R0ewdi/95sUfWJqCpvKBlUe1NsfnJS3Da02NBVzroi5j05OX49cahgDwDQCUkG+pY1TTE/W4656KoYflm2/uwrsaZDfcbauXm994Koa1ty0/p6NDxRF1dPzPsejfMm18WDDVvaTQZali0o9Y1f9nqxpazd8fZvjsfuXRST8yfXTZticF76k30ezCYZZa3RvGppTJlc3j74lidi+uKmeKNNaVDpePnT/Te3RN2sJ0r16bW/2Fb0drQvGpc9HWOL67743vpYu6Po6uCNFxti+u1zytc0cU5MmbM+mtuWJGXnWzLn8D3I9xn/0IrYmIf2jraui+nfa4j78vahcS6Ntdnqwft0eMyZDve3dP4FjfFG0V3Wfiznfe+pmN+4r+jLHKXW/rjjemFpdrz836fN8ac1RHPedyJjBgBITIKBPguNq7IkdnplDB/aOy4qlX+0xJJ/P046a22Juvufitr6XVF1ybkxY+S5Mbr/rrjv0fr4ygnXa/eOy0d9Kr6SN6sGxsLbr4z67DP6nFJnNC9bFFfP2hbN1dXxdLZ95lU9YvmiFTHmyQ7naf7vuO+h+pj03IEYVNUzhvXvXXS01/Krp7NrbIkNFf3ijuy6vz1wb3bdTbG96D9ofxZqx9zfGMtPHxgzs/M+/fV+0fzbdXH1/auLsqC8Hr4+xq/YF5+rvbh0zQvHDIhef/i/fEhHqqiK0ROGxsS8fWicw6K61NlBm/v78eqBpft7x/k9Y1efijij2CVXvea5uPZf3ooLa7J/g2v6ReVrr8eUHy6N5buLHd7F8cd10N5Y9nj5Xu3u2zNqBvWOj5/omAEAEpNeoH9tUyzKX8S87FNxea+IMy4cHLdlq4/99j87PAlub//6f4s7GyOG1V4TC79bG1Mn1saMH10X84ZGrF22/piB8gi9KmPYJQPjr/N2FrIvv+SCqMk+1X2z9f0b42cL9kbLOdUxe1pNjMi2j75pbPzk0vJ5ftN23vH23ngmLoiX5t4S9TMnxYyaoja9nc2x6OfZ8aJfzLz/hrgnu+6pt9wQC7/eu/Sk/LBtseiJbbE2m+jM/kFtjM7OO2LUdfHjUT2jpbG4Z1ngbclnAZ+ojNu+flnpmkePGRvzfjwihvXI+zvoe262T8dxntsuoB/U9v7W3zmqdH/vuf2mWDhqYLFHWeP+ATH7gcPj+Om1PbP7sCs2bC12OEJnxnVYXXYND8ycHL/O7mf9tMui8kTHDACQmOQCffNzW2J5tpx6aXW5xrpiaNR8Plu+sDkajhHKX36xJQvFPWLcFW2LvgdEzRcrsuWuWNN45Iu1J2Xr9lj2drbs25pd66ZoKH1eif198pd0s+C6pbRXoUdMm3BlDDpWsPzj9tiQTwKyiUtNPmEonHH+wBhdtEv2bouNeSg+86PxxosHz7sptn80fwzdGhua83r/AVFdnV3Hm1tizLS6eGzVlnZlQO9F+f5GjLnkOEX1+UTsE0U706/Px0rLDdvalzgd0qlxHTZs5BfihrbF/qdwzAAAHwSJBfpt0bAir7fuEds3rIiH59dnn9Wx5s08Ee+K5RuO/pLq/lKI6x1VbUJxW827u6igev9bsTFfvtAUtQ+tPPQZv6KYMPy5vCg7+vUc0tpaLtM5q8+7Phk/JDtvqQRn+7YY3+a8tT8v35P92XFyw8ZdF+snD4zL9+6K6bPq4y8nzou7lrV/j+BklO9vRQw6u7R6dL17ntjLrp0c10GDzswnaO2dqjEDAHwQpBXomzbFY6V01xp1DVtKoSz/PPxKOdTNX/Fih5rqw3r1ykP/3mju8DLpn/5c/ttBfYsg+K5Pyw/En9q8t3lMH+kRldmi5vpRsW/R5CM+d+T/m3AiehRf47hzzzFLig7t98Ur4o/vct6FIweUdoseFVFdMyoWzp0Um79fHbdVHMgmRcvjsff4e0+l2xv7YvuJlC51RmfHdSynaMwAAB8ESQX6jau3lJ5+T502qUOwGxWz8xdSm16JZ14r7XqEz35mQCloL36uTdF1a0usXZ0n9X5xeV6Wkams6lNavrGnTYJ/szGWryvaHb2dTQqKZsmQgTHx9IiG1U3tv4XlZPWvigvzucaL2+L5N8ubcvv/a3ssKdol/c+NL+X3YN0rsabNfkfVo2dUfr4mfnJrXuPeGhu2Hv1/Nzpj0JC8/r81Fq3Y1LVPvk90XMfSxWMGAPggSCfQtzZFw7NZQj69MkZcWA7fhw2MsV/NA+W+WPLcu3/1Y69Lr4qZ1dmkoH5FjJ2Zl+rUx113Px2Tsnw/fOTFMeJg6cs5lXFbHsh/sSKmzMn3WxpT7lwdayo6PrqvjOr8aXvzppj+6MqoW1wfy/Na717D4tsTKqJya2NcPa0uHl62PhpWrYzH5jwVYx/o+K0snTE4xl2fHe/tlph0Z13cl5cZzamLa+e/HoOKPcoGxribBsbwbL/a7yyIuxavi4bn1sX8+U/HlMn1xQu0r0fdD5+I6XMasvu0qXRd9y3K71fv+NL57/ZCbued8YXLYkb/7P42rIxrH1haur8Pz1oQF89/r4/BOzOuYzl1YwYA+CBIJ9C/1Bgz92YxuuZzUfMuRdj5t93kX6+4fEVT+bvHjzAgRt99XdTX9ovdG8qlOkv+2C/umVwbz7T9EaO+WTDNyzI+eSDmr9gSM1ftijO+WhuLb233pmWmX4y++eKY+snsnA2bYtLibdFcPEEeNHJcrLl9aIzptSdmzl8XtbM2xcPP7YtB51cduw7+KCq/PDa7xsq4cO+ueDC77p9tq4h7HqyNv+twSb0+PyoW/+jiuGdINrFZtD5qH1of963aHXHJwCL894xBg3rGy+say/Xo2XUtaR0Qs+8eGxOzcbwnPQbH1AdHxLwv9o7tL24r3d+Z/9EaXzrnyJr2E3X8cR3LKRwzAMAHwGnvZIr2ce3Z895eHK26dUGpROb9kP9w09W/qoh5sybEDafs12L5MMt/pGr74xOKNQCArtenz/Efjib2LTeddQIvsQIAQMK6WaDfFstLNeaL475V2Wr/qhjm6TwAAN1YNwv0+6Jx1Za4a8WuaPlkZcz72yuiuugBAIDuqJsF+qExdU75qyxf+vHYuOFT+a+JAgBA99VNa+gBAODDQaAHAICECfQAAJAwgR4AABIm0AMAQMIEegAASJhADwAACRPoAQAgYae9kynax7Vnz96idXKqbl1QtKB72P74hKIFAND1+vSpKFpH974GegAAoPM6E+iV3AAAQMIEegAASJhADwAACRPoAQAgYQI9AAAkTKAHAICECfQAAJAwgR4AABIm0AMAQMIEegAASJhADwAACRPoAQAgYQI9AAAkTKAHAICECfQAAJAwgR4AABIm0AMAQMIEegAASJhADwAACRPoAQAgYQI9AAAkTKAHAICECfQAAJAwgR4AABIm0AMAQMIEegAASJhADwAACTvtnUzRBgAAEuMJPQAAJEygBwCAhAn0AACQMIEeAAASJtADAEDCBHoAAEiYQA8AAAkT6AEAIGECPQAAJEygBwCAZEX8PyxwKEG9gVgnAAAAAElFTkSuQmCC">

**Appareil utilisé/fureteur utilisé**
 - OS: Windows 10
 - Fureteur: Edge Version 121.0.2277.98 (Version officielle) (64 bits)

**Autres informations**
- Version de l'application FRW 2024.3
- 2024-02-28 9h29

[AB#76518](https://devops700.itp.extra/700/TPM/_workitems/edit/76518)

**Comment by j0ber** [comment]
C'est une régression suite à un de nos changements pour la version 2024.3 en IT (ce n'est pas en PROD).

Ce sera corrigé sous peu. Désolé des inconvénient.

Merci d'avoir signalé le problème!

**Comment by j0ber** [comment]
C'est maintenant réglé en IT.
