### ISSUE TITLE
L’absence de balise « documentsSoumis » dans le fichier json de réception avec une pièce jointe

### ISSUE THREAD

**Issue by IhsaneRQ** [MTESSDev/FRW#206]
Bonjour,

Dans la réception d'un formulaire, nous n'avons pas la balise « documentsSoumis » pour les pièces jointes. La tâche de traiterDocumentsSoumis est bien dans notre fichier de transmission par défaut. 

Extrait de notre fichier de transmission :
 
![Ecr1](https://github.com/MTESSDev/FRW/assets/128061382/be41fa0a-85ec-4568-b48e-a8dee02cf404)

Le fichier json de réception avec une pièce jointe et l’absence de balise « documentsSoumis »
 
![Ecr2](https://github.com/MTESSDev/FRW/assets/128061382/0ecdbf55-635e-412f-a3a1-bfae64621c31)

Merci et bonne journée

[AB#76572](https://devops700.itp.extra/700/TPM/_workitems/edit/76572)

**Comment by LarcM7** [comment]
Bonjour,
S'il vous plaît la prochaine fois inclure le nom du formulaire et le numéro du système autorisé ça facilite nos vérifications.

J'ai déduit que vous utilisiez le formulaire TIT-003-001-STA du système 240003.

J'ai ouvert celui-ci et cliqué sur TesterTransmission et je vois bien "documentsSoumis" : 

![image](https://github.com/MTESSDev/FRW/assets/129791924/5a5ddbfc-f71a-4d63-9d86-b743c9b2173e)

Serait-elle plus bas dans le contenu que l'on voit dans votre capture d'écran?

**Comment by claveaal1** [comment]
Bonjour,

Nous avons regradué les templates ce matin et avons fait plusieurs tests, nous n'avons pas la balise documentSoumis

Est-ce possible nous contacter svp

**Comment by LarcM7** [comment]
Personnellement je n'ai pas vos informations de contact. 

Nous privilégions l'utilisation de GitHub pour la résolution des problèmes.

La démarche et les réponses peuvent être utiles à d'autres personnes.

Je n'ai toujours pas les informations telles que le ou les formulaires concernés et le numéro du système autorisé.

Est-ce que vous confirmez avoir vérifié le comportement avec le bouton "TesterTransmission"? 

- Dans la section "Message des tâches", 
- sous "AppelerServiceExterne->appel_externe->Body"
- à la toute fin en bas à la suite de l'énorme domaine de valeurs 

![image](https://github.com/MTESSDev/FRW/assets/129791924/c8c311d8-891d-40df-b43c-a16e9ed63dd0)

De mon côté je vois documentSoumis. Si je suis dans le bon formulaire du bon système autorisé...

Merci

**Comment by IhsaneRQ** [comment]
Le formulaire utilisé est bien : TIT-003-001-STA et le système est : 240002

Quand on fait "TesterTransmission", on voit la balise mais pas dans ce qu'on reçoit dans le Json : 

{"form":{"NumClient":9997,"TypeClient":"cli","Nom":"toto","Prenom":"toto","Langue":"fr","NumSessionClicSecur":"123","ValeurIdentifiantFormulaireWebAig":null,"DateNaissance":null,"RegimesRRSP":[],"EtatRevision":"sans-erreur","validAll":true,"PjManquantes":[{"cle":"SpecimenCheque[0]","sectionName":"ExemplePieceJointe","nomDocument":"Spécimen de chèque (1)"}],"Groupe_ActeNaissance":[{"actenaissance":[{"url":"6NkZQPAW2EsJ3AlBBXVQtAR7Vj8jG4u6XyXjXZOZuLEnA8qQP9u1xJkz2gkw.pdf","name":"Contenu.pdf","_type":"customFile"}]}],"Groupe_SpecimenCheque":[{"SpecimenCheque_TransmissionUlterieure":true,"SpecimenCheque":"ulterieure"}],"Signature":"Test","DateSignature":"2024-02-29"},"systeme":{"infosEnregistrement":{"courriel":"test@test.com"}},"config":null,"X-NoConfirmation":370958311,"X-DateTransmission":"2024-02-29T13:19:58.9577995"}

**Comment by vinnyboii** [comment]
Bonjour,

La fonctionnalité "Tester transmission" reflète exactement les données que FRW fourni lors de la transmission.

Je ne sais pas trop de quel JSON vous faites référence dans votre dernier message, mais est-ce que ça se pourrait que la propriété "DocumentSoumis" ne soit pas mappée dans votre traitement qui produit ce JSON?

Bonne journée

**Comment by loima02** [comment]
Salut @claveaal1 !

L'URL à utiliser est lui dans "documentsSoumis" ici :
![image](https://github.com/MTESSDev/FRW/assets/35601944/0f891e38-b02d-4801-8f2e-186b8b7f60ba)
