### ISSUE TITLE
Ajouter etape dans le schéma des formulaires

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#207]
La propriété etape de l'aiguillage du mode redirectionProchainUtilisateur est en erreur dans le schéma.

![image](https://github.com/MTESSDev/FRW/assets/43148349/4f8e7195-8798-4a02-9c59-99440b948a18)

[AB#76984](https://devops700.itp.extra/700/TPM/_workitems/edit/76984)

**Comment by FujuDev** [comment]
Bonjour,

Merci d'avoir remarqué cela, nous allons ajouter l'autocomplétion de l'étape prochainement!

**Comment by FujuDev** [comment]
Le correctif a été monté en IT, et l'étape devrait désormais être disponible dans le schéma.
