### ISSUE TITLE
Bloc adresse internationale non optionnel

### ISSUE THREAD

**Issue by jodionrq** [MTESSDev/FRW#209]
### Discussed in https://github.com/MTESSDev/FRW/discussions/208

<div type='discussions-op-text'>

<sup>Originally posted by **jodionrq** March  7, 2024</sup>
Bonjour,
J'ai un bloc d'adresse internationale que je dois rendre optionnel.
Mon champ "Adresse" est bien optionnel (pas d'astérisque rouge), mais le bloc en soi semble rester obligatoire.
![image](https://github.com/MTESSDev/FRW/assets/124822406/2cdaf582-9377-46a1-8b37-39f42b4b6795)
Pouvez-vous regarder s'il s'agit bien d'un bogue?</div>

[AB#77079](https://devops700.itp.extra/700/TPM/_workitems/edit/77079)

**Comment by vinnyboii** [comment]
Bonjour,

Effectivement nous avons constaté qu'il y a cette limitation avec les contrôles d'adresse dans FRW.

Après avoir évalué l'ampleur de la modification, nous avons décidé de laisser les contrôles d'adresse (standard et international) obligatoires. Nous allons donc modifier la documentation en ce sens.

Pour régler votre problème, nous vous suggérons d'ajouter une question pour conditionner l'affichage de ce contrôle d'adresse afin qu'il soit affiché seulement lorsque nécessaire.

Merci et bonne journée!

**Comment by jodionrq** [comment]
Bonjour,
Merci pour le retour, c'est noté.
Bonne journée
