### ISSUE TITLE
Problème de caractères accentués avec le paramètre texteBoutonSoumettre

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#21]
Le paramètre suivant ne s'affiche pas bien dans le formulaire lorsqu'il y a des caractères accentués.

config:  soumission:    texteBoutonSoumettre

![2023-02-23 09_54_08-Window](https://user-images.githubusercontent.com/43148349/220943977-950bf182-861b-458e-ab2b-371734903fa7.png)
![2023-02-23 09_54_51-Window](https://user-images.githubusercontent.com/43148349/220943983-29ad2117-aa32-4b62-8c91-efb82fffb6dd.png)

**Comment by j0ber** [comment]
Problème corrigé.
