### ISSUE TITLE
Permettre d'inclure la valeur d'un champ dans le courrielProchainUtilisateur

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#210]
Le MTRAV aimerait pouvoir ajouter la valeur d'un champ du formulaire dans le courriel envoyé au prochain utilisateur.
config:
  courrielProchainUtilisateur:
    nomExpediteur: Services en ligne MTRAV
    objet: '{0} - Demande à valider'
    corps: |
      Bonjour,
      <strong>Type de demande : </strong>{{form_typeDemande}}
      Cordialement,

[AB#77139](https://devops700.itp.extra/700/TPM/_workitems/edit/77139)

**Comment by anisite** [comment]
Bonjour, 

Nous vous suggérons d'utiliser des termes génériques plutôt que d'inclure des parties variable dans le courriel d'aiguillage, au besoin il est possible d'utiliser plus d'un aiguillage de type "prochain utilisateur" avec des conditions différentes, si par exemple vous avez deux type de demande dans un seul formulaire cela pourrait vous dépanner, mais le formulaire d'aiguillage n'est pas prévu actuellement servir de résumé de demande ou être remplis d'informations spécifique, il est conçu sur la base d'un simple lien de "reprise". 

Ce besoin n'est pas écarté mais ce n'est pas prioritaire actuellement, à moins d'avis contraire.

**Comment by drogu02** [comment]
Je comprend que je pourrais faire plusieurs redirections différentes. Par contre, je ne vois pas comment je pourrais changer le contenu ou l'objet du courriel.

config:
  courrielProchainUtilisateur:
    nomExpediteur: Services en ligne MTRAV
    objet: '{0} - Demande à valider'
    corps: |
      Bonjour,
      Suite du message ...
      
aiguillage:
    choix:
      - mode: redirectionProchainUtilisateur
        vif: val('etape') != 'etape2' && val('typeDemandePrecision') == 'tra0003'
        formulaire: MTRAV-Formulaires
        champCourriel: courrielProchaineEtape
        champMotDePasse: motDePasseProchaineEtape
        etape: etape2
      - mode: redirectionProchainUtilisateur
        vif: val('etape') != 'etape2' && val('typeDemandePrecision') == 'tra0004'
        formulaire: MTRAV-Formulaires
        champCourriel: courrielProchaineEtape
        champMotDePasse: motDePasseProchaineEtape
        etape: etape2

**Comment by drogu02** [comment]
Le client a décidé de mettre un texte générique!
