### ISSUE TITLE
Contrôle de coordonnées bancaires

### ISSUE THREAD

**Issue by florentarneodo** [MTESSDev/FRW#211]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Non, pas un problème, amélioration générale

**Décrivez votre besoin**
On demande dans nos formulaires le compte en banque du client pour s'inscrire au dépôt direct. Il existe des validations possibles que l'on peut faire pour voir si c'est un compte en banque qui peut exister (contrôle de coordonnées bancaires).

**Décrivez les alternatives que vous avez envisagées**
Retraite Québec le fait déjà pour des services, mais on ne semble pas pouvoir le reporter dans FRW à notre niveau.

**Proposition de solution**
On pourrait vous envoyer ce que l'on fait déjà pour valider un compte en banque et vous pourrez créer un module qui fait le nécessaire pour tous les clients de FRW (comme le module de NAS par exemple)

**Contexte supplémentaire**
![image](https://github.com/MTESSDev/FRW/assets/140817361/e3ea3f16-7b1c-420e-94a4-3fafa8e77c16)

[AB#77387](https://devops700.itp.extra/700/TPM/_workitems/edit/77387)

**Comment by Ghost3044** [comment]
Bonjour Florent, nous en parlerons lors de notre rencontre d'arrimage de lundi le 18 mars. Nous avons quelques questions à valider avec vous pour bien cerner votre besoin.

**Comment by j0ber** [comment]
Bonjour,
Nous sommes en train de développer le contrôle en se basant sur le vôtre.
Nous aimerions savoir pourquoi on devrait permettre un tiret dans le champ "Compte" ?
Il suffirait d'indiquer à l'utilisateur de saisir sans tiret.

Le tiret est inutile non?
Sachant que plus de 50% des utilisateurs sont en mobile, un champ numérique (comme les deux autres) permettrait d'avoir un clavier numérique permettant la saisie.

Bref, nous aimerions savoir pourquoi vous avez conservé ça.

Merci!

**Comment by PhilippeLRETQC** [comment]
Nous sommes en cours de vérification et nous vous revenons dès que possible sur la raison.

**Comment by j0ber** [comment]
Super merci!

**Comment by vinnyboii** [comment]
Bonjour,
Est-ce qu'actuellement vous gérez toutes les institutions financières répertoriées dans le fichier des institutions financières du canada? (https://www.paiements.ca/ressources/repertoires?field_directory_type=11)

Merci!

**Comment by florentarneodo** [comment]
Salut,
J'ai compris que ça date de la "Liste des structures de numéro de compte et critères de validation" d'avril 2013 de "Association canadienne des paiements". Certaines banques ne sont même pas membre de l'ACP. Pensons aux nouvelles banques électronique comme Tangerine qui peuvent sortir d'un certain cadre.
Il faut donc laisser une certaine latitude.
Si vous voyez des améliorations, c'est sûrement bon.
Avec tout l'argent que Retraite Québec envoie, ça se saurait s'il y avait des problèmes avec le système.
Bonne journée.

**Comment by j0ber** [comment]
Vous pouvez tester le contrôle ici : https://formulaires.it.mtess.gouv.qc.ca/fr/Form/7/TEST_INFOS_BANCAIRES/0/N#p=1.

Pour le moment il n'y a pas de vraie information du FIF. Pour avoir des valeurs valides, il faut saisir des informations avec le même chiffre. (ex. 11111, 222, 33333 etc.)

Pour tester une vérification en erreur, simplement saisir un bon format, mais avec des chiffres qui ne sont pas tous identiques, ex. 11112, 223, etc.

Vous pouvez également intégrer le contrôle dans vos formulaires, et regarder la structure en sortie, ça ne devrait pas changer.

**Comment by anisite** [comment]
Nouvelle structure du contenu retourné pour un champ de type ``infosBancaires``
 ````json
{
  "Succursale": "12345",
  "InstitutionFinanciere": "123",
  "Compte": "1234567890"
} 
````
L'interface qui sera livrée : 
![image](https://github.com/MTESSDev/FRW/assets/3194288/6526c914-a0d6-420a-b0e0-31e0c91d3c9a)

**Comment by anisite** [comment]
@florentarneodo  nous fermons l'issue mais n'hésitez pas à en ouvrir un autre si vous rencontrez des problèmes durant vos essais. 

Merci!
