### ISSUE TITLE
Utiliser la version 2.1.1 des composants UTD

### ISSUE THREAD

**Issue by j0ber** [MTESSDev/FRW#212]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
En deux mots... Non.

**Décrivez votre besoin**
Simplement utiliser la version 2.1.1 des composants UTD.
Notamment afin d'avoir la nouvelle version du composant "PIV entête" qui contient des ajustements mineurs (version publiées officiellement dans le SDG fin novembre 2023)

**Décrivez les alternatives que vous avez envisagées**
N/A

[AB#77391](https://devops700.itp.extra/700/TPM/_workitems/edit/77391)

**Comment by loima02** [comment]
C'est en PROD!
