### ISSUE TITLE
Pouvoir utiliser l'enregistrement avec compte mot de passe dans un formulaire prérempli dans un site anonyme

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#217]
Dans un formulaire pour le MTRAV qui est utilisé dans un site Internet **anonyme**, j'utilise la fonctionnalité de pré-remplissage mais je ne peux pas utiliser la fonctionnalité d'enregistrement car ça l'enregistre le formulaire sans demander de compte et mot de passe.

Est-ce que ce serait possible de faire que la fonctionnalité d'enregistrement fonctionne comme dans un formulaire anonyme même s'il y a eu du pré-remplissage!

Pour l'instant, j'ai désactivé la fonctionnalité d'enregistrement, alors ce n'est pas un besoin pressant.

[AB#78498](https://devops700.itp.extra/700/TPM/_workitems/edit/78498)

**Comment by LarcM7** [comment]
Je pense que ceci pourrait être une piste de solution. 

https://github.com/MTESSDev/FRW/issues/40

Non-priorisée pour l'instant à ma connaissance.

**Comment by LarcM7** [comment]
En attendant est-ce que les informations que vous avez à préremplir pourraient être placées différemment dans le formulaire?

**Comment by drogu02** [comment]
Non pas vraiment, mais le client a accepter de désactiver l'enregistrement. Donc, si vous mettez en place cette amélioration, je l'utiliserai, sinon ce n'est pas critique.

**Comment by LarcM7** [comment]
duplicate 
https://github.com/MTESSDev/FRW/issues/40
