### ISSUE TITLE
Retirer ``contenuFormulaireJson`` du contenu lors de la transmission à un système autorisé

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#218]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Oui, le contenu en sortie est trop gros pour être preview dans les outils et contient de l'information redondante.

**Décrivez votre besoin**
Réduire la taille du contenu passé aux services et affiché dans les outils de dev.

**Décrivez les alternatives que vous avez envisagées**
Ne rien faire, mais par contre ça rend le contenu très gros.

**Propostion de solution**
Il faudrait enlever le bloc ``contenuFormulaireJson`` du contenu en sortie dans FRW333.

https://github.com/MTESSDev/FRW/blob/da0a26b67b9c4c81d3fb6e327dedb7317d0204c3/Documentation/fichiers-transmission.md#variables-et-contenu

**Contexte supplémentaire**
![image](https://github.com/MTESSDev/FRW/assets/3194288/a525cb62-f4be-4046-a3f4-5b7cb9e600ff)

[AB#78555](https://devops700.itp.extra/700/TPM/_workitems/edit/78555)

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
