### ISSUE TITLE
Augmenter la taille maximale permise dans le contrôle de pièces jointes

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#219]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Le système GED a besoin de pouvoir déposer des fichiers ÉNORMES en provenance de son dépôt manuel. (Jusqu'à 313mo selon julie).
  
**Décrivez votre besoin**
Pouvoir déposer des gros fichiers.

**Propostion de solution**
Changer la façon de chiffrer les fichiers sur le répertoire temporaire.
Utiliser le stream au lieu du byte pour les fichiers

[AB#78583](https://devops700.itp.extra/700/TPM/_workitems/edit/78583)

**Comment by loima02** [comment]
C'est en IT!
