### ISSUE TITLE
Documenter les types de champs "CP12" et "CodePostal"

### ISSUE THREAD

**Issue by j0ber** [MTESSDev/FRW#223]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Non

**Décrivez votre besoin**
Documenter les types de champs "CP12" et "CodePostal".
Ils sont actuellement très discrets dans la page du champ "Texte".

Ils devraient avoir leur propre page, comme NAS, NAM, tel,  etc.

[AB#79427](https://devops700.itp.extra/700/TPM/_workitems/edit/79427)

**Comment by Ghost3044** [comment]
Changement fait
