### ISSUE TITLE
Ajouter une propriété aux champs qui permettrait de transformer les lettres en lettres minuscules ou majuscules.

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#224]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Non

**Décrivez votre besoin**
Transformer les lettres vers des majuscules ou minuscules à la sortie d'un champ.

**Décrivez les alternatives que vous avez envisagées**
Je suis capable de le faire avec des computed et watch mais @j0ber considère que ce serait beaucoup plus intéressant et facile de faire cela avec une propriété additionnelle aux champs. 

**Propostion de solution**
Ajouter une propriété aux champs qui permettrait de transformer les lettres en lettres minuscules ou majuscules.

**Contexte supplémentaire**
Aucun

[AB#79428](https://devops700.itp.extra/700/TPM/_workitems/edit/79428)

**Comment by loima02** [comment]
C'est en IT!

**Comment by drogu02** [comment]
Est-ce que vous avez déjà mis dans dans la doc sur ce site?
https://formulaires.it.mtess.gouv.qc.ca/Form/7/P700U/0/N

**Comment by j0ber** [comment]
C'est en IT. 

Le guide d'utilisation a été mis à jour https://formulaires.it.mtess.gouv.qc.ca/fr/Form/7/P700U/0/N/#p=controlesBase. 
Voir exemples 9 et 10.

Sera normalement en PROD le 8 octobre 2024.

**Comment by loima02** [comment]
C'est en PROD!
