### ISSUE TITLE
customfileUlterieure : Pièce jointes supprimées lors de transmission

### ISSUE THREAD

**Issue by jodionrq** [MTESSDev/FRW#228]
**Description du problème**
Nous avons utiliser des contrôles de customfileUlterieure pour offrir la possibilité d'envoyer une pièce jointe plus tard. Tout va bien jusqu'à la validation, mais lors de la transmission, voici ce qui se produit : 
Si on coche "Je transmettrai ces documents plus tard", tout fonctionne et le formulaire se transmet.
Si on ajoute une pièce jointe, la pièce jointe disparait. Le formulaire devient incomplet et on ne peut pas le transmettre.

**Étapes pour reproduire le bogue**
1. Aller à sur la page d'outils FRW, dans le système 240002
2. Cliquer sur 'LPF-800-001-STA'
3. Donner des réponses les plus simples pour ne pas faire apparaitre trop de questions. Lorsque vous arrivez aux renseignements sur l'enfant, ajouter une pièce jointe pour donner un document de preuve pour l'enfant.
4. Aller jusqu'à la transmission. Vous ne serez pas en mesure de transmettre le formulaire (vous aurez soit un message d'erreur ou soit que la page va tourner en boucle).

**Comportement attendu**
On devrait être capable de transmettre la demande, ou du moins aviser les utilisateurs qu'un contrôle manque une pièce jointe.

**Captures écran**
Exemple avant la transmission : l'objet "preuvePresenceEnfant2" contient une pièce jointe
![image](https://github.com/MTESSDev/FRW/assets/124822406/cb900791-f57d-4dda-8742-ea03980675c3)

Après "tester transmission" : l'objet "preuvePresenceEnfant2" a complètement disparu.
![image](https://github.com/MTESSDev/FRW/assets/124822406/35002bf4-6b7a-4b94-b332-9ee76b045b25)

De plus, d'une fois à l'autre, à la page de transmission, la page tourne en boucle et le message qu'il manque une pièce jointe n'apparait pas. C'est seulement lorsqu'on retourne dans le formulaire qu'on remarque qu'il y a effectivement une erreur.

**Appareil utilisé/fureteur utilisé**
 - OS: Windows 10
 - Fureteur: Edge version 123 64 bits

**Autres informations**
- Version de l'application FRW 2024.5
- Vendredi 19 avril 2024, 12:08

[AB#80141](https://devops700.itp.extra/700/TPM/_workitems/edit/80141)

**Comment by anisite** [comment]
@jodionrq J'ai retiré le lien vers votre page de gestion des formulaires, par sécurité, et supprimé l'historique. On regarde ce matin pour votre questionnement/bug merci.

**Comment by jodionrq** [comment]
Super, merci!

**Comment by j0ber** [comment]
Vous pouvez réessayer, le problème devrait être réglé en IT.
Merci!

**Comment by jodionrq** [comment]
Ça fonctionne, merci!
