### ISSUE TITLE
 Modifier le lien par défaut du titre dans la bande bleue (en-tête) des formulaires

### ISSUE THREAD

**Issue by ageliinas** [MTESSDev/FRW#237]
Bonjour,
Nous avons reçu la demande de pouvoir changer le lien URL du titre qui se trouve dans la bande bleue des formulaires (en-tête) à côté du logo afin d'y ajouter le lien vers notre page d'accueil du site web de Retraite Québec. Pour l'instant, ce lien pointe vers https://www.quebec.ca/ par défaut.

![image](https://github.com/MTESSDev/FRW/assets/80847091/96e976d3-870d-43e0-a5de-b3cc38d39a39)

Il ne semble pas y avoir d'options pour changer ce lien dans le code. Nous avons testé d'ajouter urlLien comme pour Nous Joindre, mais ce n'était pas concluant.

![image](https://github.com/MTESSDev/FRW/assets/80847091/68a680ae-37ae-48b2-a420-9361a0b59a32)

[AB#81107](https://devops700.itp.extra/700/TPM/_workitems/edit/81107)

**Comment by Ghost3044** [comment]
Bonjour,

Merci pour votre demande concernant les modifications des liens dans la bande bleue des formulaires. Nous ferons les modifications suivantes: 

- Le logo du gouvernement du Québec redirigera les utilisateurs vers la page québec.ca.
- Le lien du logo de Retraite Québec pourra ramener les utilisateurs vers la page d'accueil de Retraite Québec.

Nous prioriserons cette issue dans l'un de nos prochains sprints.

Restez à l'affut!

**Comment by ageliinas** [comment]
C'est testé et fonctionnel, merci! :)

**Comment by loima02** [comment]
C'est en PROD!
