### ISSUE TITLE
Erreur lors de la production du fichier (genererWord) avec une date vide

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#240]
**Description du problème**
La transmission d'un formulaire est bloquée pour le formulaire RSP-727-001-STA de Retraite Quebec.

Le problème est celui ci: System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.DateTime'.

C'est causé par un champ date optionnel qui a été **rempli et vidé** durant la complétion du formulaire. Il a donc la valeur "" dans le modèle de données.

Voici un exemple:
![image](https://github.com/MTESSDev/FRW/assets/128411313/f3173d7c-7c9c-46e7-8577-0b0b177dfb48)
![image](https://github.com/MTESSDev/FRW/assets/128411313/a827246f-7608-4612-b398-631b5498f080)

**Comportement attendu**
Que le champ vide soit interprété comme étant NULL et qu'on lui associe la valeur "S.O" comme on le fait pour les autres champs optionnels qui sont NULL.

[AB#81500](https://devops700.itp.extra/700/TPM/_workitems/edit/81500)

**Comment by vinnyboii** [comment]
> On fix dans générerWord pour passer la valeur brute quand le cast ne passe pas?
> 
> On nettoie le modèle avant transmission?

Ce sont les 2 options que j'avais en tête. J'aime bien nettoyer le modèle avant transmission.

**Comment by anisite** [comment]
le fix est dispo dans une branche, à tester @LarcM7 @vinnyboii

**Comment by LarcM7** [comment]
c'est concluant

**Comment by anisite** [comment]
C'est en IT
