### ISSUE TITLE
Transmission s'effectue en cas d'erreur

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#242]
**Description du problème**
Si une transmission est effectuée au moment où le serveur de fichier ne répond pas, la page de confirmation est affichée normalement avec un numéro de confirmation, mais la transmission du formulaire n'est jamais inscrite dans l'asynchrone.

**Étapes pour reproduire le bogue**
1. Compléter un formulaire sans le transmettre
2. changer la configuration du serveur de fichier
3. transmettre le formulaire
4. Page de confirmation en succès
5. Rien dans l'asynchrone pour le formulaire qui a été transmis :(

**Comportement attendu**
L'interface ne devrait pas permettre la transmission si le serveur de fichier n'est pas disponible.

[AB#81703](https://devops700.itp.extra/700/TPM/_workitems/edit/81703)

**Comment by anisite** [comment]
Après investigation, il semble que cela était du à un nouveau bug introduit dans une story, qui a été corrigé dans le cadre de #241
