### ISSUE TITLE
Bloquer le coller dans un champ "validations: confirm"

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/FRW#244]
**Décrivez votre besoin**
Nous souhaitons obliger les utilisateurs à retaper une valeur dans le champ "validations: confirm" pour éviter qu'il fasse un copier/coller d'une valeur étonnée. Par exemple forcer de taper le mot de passe de confirmation ou le courriel de confirmation.

**Décrivez les alternatives que vous avez envisagées**
Créer un javascript personnaliser et l'injecter nous même.

**Proposition de solution**
Ajouter un attribut "additionnals" du genre "bloquerColler: true" dans la configuration qui pourrait bloquer le coller dans un champs. Cet attribut pourrait aussi être utiliser sur tous les champs texte ou numérique pas seulement sur les champs "validations: confirm"

**Contexte supplémentaire**
Il n'y a pas d'urgence à réaliser cette demande

Merci

[AB#82566](https://devops700.itp.extra/700/TPM/_workitems/edit/82566)

**Comment by Ghost3044** [comment]
Bonjour,
Nous allons prioriser cette issue dans l'un de nos prochains sprints dans l'été.

**Comment by loima02** [comment]
C'est en IT!

**Comment by j0ber** [comment]
C'est en IT. 

Le guide d'utilisation a été mis à jour https://formulaires.it.mtess.gouv.qc.ca/fr/Form/7/P700U/0/N/#p=controlesBase. 
Voir exemple 11.

Sera normalement en PROD le 8 octobre 2024.

**Comment by loima02** [comment]
C'est en PROD!
