### ISSUE TITLE
Fonction val() problème avec un index inexistant

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#249]
Voici un problème que j'ai trouvé et confirmé avec Christian.

v-if: val(`groupeRepresentantsEmployeur.courrielRepresentantEmployeur`, 5)

retourne la valeur de l'index 0 si l'index 5 n'existe pas.

Je m'attendrais à recevoir un undefined.

[AB#82663](https://devops700.itp.extra/700/TPM/_workitems/edit/82663)

**Comment by loima02** [comment]
C'est en PROD!
