### ISSUE TITLE
Bug dans liens URL dans un Tooltip d'une liste déroulante

### ISSUE THREAD

**Issue by ageliinas** [MTESSDev/FRW#253]
Bonjour,
Nous avons trouvé un bug lorsque nous utilisons une liste déroulante et une infobulle (tooltip) avec un lien URL à l'intérieur de celle-ci. Le lien n'est pas cliquable, mais il peut être ouvert en faisant un clic droit, ce qui montre que l'URL est correcte. Ce bug est présent dans le RSP-079-AIG et le RSP-009-STA.

Voici le code:

![image](https://github.com/MTESSDev/FRW/assets/80847091/d8f99325-1b80-440d-96d6-894bdf2f88f4)

Voici visuellement dans le formulaire:

![image](https://github.com/MTESSDev/FRW/assets/80847091/f5681b30-537b-41ab-98a2-811e128c303f)

Merci,
Bonne journée!

[AB#82738](https://devops700.itp.extra/700/TPM/_workitems/edit/82738)

**Comment by Ghost3044** [comment]
Bonjour,
Le fix devrait monter en IT lundi. Une fois que nous aurons votre confirmation, nous planifierons la mise en prod. 
Bonne journée!

**Comment by ageliinas** [comment]
testé et fonctionnel

**Comment by loima02** [comment]
C'est en PROD!
