### ISSUE TITLE
Problème avec le nouveau champ infosBancaires

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#257]
Dans le fichier Word ou PDF généré, il faudrait tenir compte des « 0 » pour l’affichage du numéro de compte comme avant, car ça pourrait porter confusion pour l’agent. Dans cet exemple, le numéro de compte est le 0033225.  Les 00 sont tronqués dans le fichier.

![image](https://github.com/MTESSDev/FRW/assets/43148349/7751251f-88bf-43b3-a9fd-058294021331)

[AB#83059](https://devops700.itp.extra/700/TPM/_workitems/edit/83059)

**Comment by anisite** [comment]
<img width="309" alt="image" src="https://github.com/MTESSDev/FRW/assets/3194288/178e2d7c-4d4b-428e-92b1-21b50d8157d0">
@drogu02  t'a aussi un mini typo :)

**Comment by drogu02** [comment]
Bonjour!  Quand pensez-vous effectuer la correction? Je me le fais demander par un client!

**Comment by Ghost3044** [comment]
Bonjour,

La correction a été montée en prod aujourd'hui. 

N'hésitez pas si vous avez besoin d'autre chose!

**Comment by drogu02** [comment]
Ok parfait merci!

**Comment by drogu02** [comment]
Le problème est toujours là en IT

![image](https://github.com/MTESSDev/FRW/assets/43148349/c817aa44-9ffb-4f39-a6c0-72683a688fa9)

**Comment by drogu02** [comment]
C'est beau en IT maintenant!
