### ISSUE TITLE
Améliorer le retour du service CreerFormulaireIndividu quand le formulaire n'est pas déployé ou absent

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#258]
**Description du problème**
Le message est imprécis

````json
{"DateHeure":"05/28/2024 12:09:18","EventId":{"Id":13,"Name":"ApplicationError"},"Level":4,"LevelNom":"Error","Type":0,"TypeNom":"Application","Contenu":"Connection id \"0HN3V5UR5JP5T\", Request id \"0HN3V5UR5JP5T:00000002\": An unhandled exception was thrown by the application.","Informations":{"NomServeur":"api-7444c74ffb-wjt5g","Environnement":"Production","NomApplication":"CommunicationClientele.FormulairesWeb.Api","Emplacement":"Microsoft.AspNetCore.Server.Kestrel","ContexteHttp":{"InformationContexteDisponible":false}},"Exception":{"StatusCode":500,"Response":"{\"No\":\"500\",\"Message\":\"Objet erreur reÃ§u seul\",\"Cible\":\"/api/v1/SIS/CreerFormulaireIndividu/TIT-001-001-STA\
````

**Étapes pour reproduire le bogue**
1. Appeler /api/v1/SIS/CreerFormulaireIndividu/XYZ

**Comportement attendu**
Avoir une erreur 400 ou 500 avec "formulaire introuvable" ou quelque chose comme
**Captures écran**

**Appareil utilisé/fureteur utilisé**
 - OS: (ex: Windows 10)
 - Fureteur: (ex: Chrome 111)

**Autres informations**
- Version de l'application FRW (inscrite au bas de la page)
- Date/heure de l'événement (au plus précis possible)

[AB#83065](https://devops700.itp.extra/700/TPM/_workitems/edit/83065)

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
