### ISSUE TITLE
Ajout d'un contrôle sur le libellé et lien du "Copyright" au bas des formulaires

### ISSUE THREAD

**Issue by jodionrq** [MTESSDev/FRW#260]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Nous n'avons pas de contrôle sur le Copyright au bas des pages des formulaires.
![image](https://github.com/MTESSDev/FRW/assets/124822406/54976295-002a-4f09-8f7c-04d91cb5e9a5)

**Décrivez votre besoin**
Nous aimerions pouvoir modifier le texte qui apparait dans le bas des pages de formulaire "© Gouvernement du Québec" ainsi que le lien URL. Il pointerait vers une page des droits d'auteur de Retraite Québec.

**Contexte supplémentaire**
Si ce n'est pas possible, que pouvez vous nous suggérer?
Si jamais on doit passer par vous, nous aimerions retirer l'année. 
Voici les liens que nous aimerions avoir :
Français:
https://www.retraitequebec.gouv.qc.ca/fr/Pages/droits-auteur.aspx 
Anglais:
https://www.retraitequebec.gouv.qc.ca/en/Pages/droits-auteur.aspx 

Merci!

[AB#83142](https://devops700.itp.extra/700/TPM/_workitems/edit/83142)

**Comment by Ghost3044** [comment]
Bonjour,
Dans le but de garder notre solution générique, nous préférons ne pas rendre configurable le lien du copyright dans le bas des pages des formulaires. Sachant, qu'il n'y a pas de contraintes légales entourant ce besoins, nous préférons garder la solution comme elle est actuellement. 
Si vous avez des utilisateurs qui manifestent ce besoin, simplement nous faire signe et nous pourrons reconsidérer l'ajustement.
Bonne journée!

**Comment by jodionrq** [comment]
D'accord, merci pour le retour.
Bonne journée!
