### ISSUE TITLE
Bug affichage spinner sans fin si erreur lors du nettoyage du modèle

### ISSUE THREAD

**Issue by j0ber** [MTESSDev/FRW#261]
**Description du problème**
Dans la page révision, si la révision est automatique selon la configuration (donc pas de bouton "Valider" ou "Réviser") et qu'on a une erreur lors du nettoyage du modèle de données côté serveur, une erreur technique est affichée, mais le spinner reste présent.

**Étapes pour reproduire le bogue**
Bonne chance... au pire le forcer dans le code côté front.
Constaté dans #247 .

Problème qui devrait rarement se produire.

**Comportement attendu**
Le spinner devrait disparaître une fois l'erreur technique affichée.

[AB#83212](https://devops700.itp.extra/700/TPM/_workitems/edit/83212)

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
