### ISSUE TITLE
Contrôle d'informations bancaires - Affichage qui bouge en contexte d'une validation en erreur

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#262]
**Description du problème**
Lorsqu'il y a une erreur dans le contrôle d'info bancaire, il est impossible de cliquer sur le bouton "Vérifier" puisque le message de validation disparait quand on corrige l'erreur de validation. La page bouge et le click ne fonctionne pas.

**Étapes pour reproduire le bogue**
1. Prendre un formulaire avec un contrôle bancaire
2. remplir les champs en mettant au moins une erreur
3. Cliquer sur vérifier
4. Voir l'erreur de validation
5. Corriger le champ en erreur en mettant toujours une autre valeur invalide
6. Cliquer sur vérifier
7. BANG! la page remonte et on ça prend un 2e click.

**Comportement attendu**
Juste un click SVP. Ma souris est fragile.

[AB#83214](https://devops700.itp.extra/700/TPM/_workitems/edit/83214)

**Comment by loima02** [comment]
C'est en PROD!
