### ISSUE TITLE
Afficher le sous-titre dans le PDF du formulaire

### ISSUE THREAD

**Issue by billo04** [MTESSDev/FRW#267]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Oui.

**Décrivez votre besoin**
Le sous-titre doit être présenté dans le PDF du formulaire lors de sa soumission tout comme le titre l'est.

**Décrivez les alternatives que vous avez envisagées**
Le sous-titre peut être inséré dans la zone d'estampe, mais il pourrait y avoir trop d'information ce qui ferait que l'estampe s'affiche par-dessus du contenu du formulaire.

**Propostion de solution**
Sans objet.

**Contexte supplémentaire**
![image](https://github.com/MTESSDev/FRW/assets/124705516/b7b6338c-87b4-4ede-b861-485b1ce3734b)

[AB#83889](https://devops700.itp.extra/700/TPM/_workitems/edit/83889)

**Comment by Ghost3044** [comment]
Bonjour, 

Merci pour votre demande. Nous allons prioriser cette issue rapidement.

Restez à l'affut!

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
