### ISSUE TITLE
Optimiser l'enregistrement automatique des formulaires

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#269]
**Décrivez votre besoin**
Optimiser les MAJ lors de la navigation dans un formulaire afin de moins surcharger le système d'appels en "MAJ".

**Propostion de solution**
Sur le changement de section, effectuer la MAJ seulement si un changement a été détecté dans la section.

[AB#84183](https://devops700.itp.extra/700/TPM/_workitems/edit/84183)

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
