### ISSUE TITLE
Permettre l'enregistrement avec courriel et mot de passe pour un formulaire ouvert avec l'API CreerFormulaireIndividu

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#270]
Dans les formulaires que j'ai créé pour le MTRAV, j'utilise l'API CreerFormulaireIndividu pour pré-remplir des champs mais je ne suis pas associé à un utilisateur car je suis sur un site Internet.

Quand j'active l'enregistrement pour ce formulaire, ça l'enregistre sans demander le courriel et mot de passe.

Est-ce que ce serait possible de demander le courriel et mot de passe au lieu d'enregistrer automatiquement si le paramètre X-IdentifiantUtilisateur est vide et/ou absent ou si il est défini à anonyme.

Les gens du MTRAV aimeraient bien cette possibilité puisque les formulaires sont assez longs à remplir.

[AB#84193](https://devops700.itp.extra/700/TPM/_workitems/edit/84193)

**Comment by anisite** [comment]
Il existe une demande semblable #40
