### ISSUE TITLE
BREAKING - Retrait du support des fichiers ODT transmis - Composant pièces jointes - Enjeu de sécurité V4

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#275]
Un enjeu de sécurité a été remonté pour les ODT, ils ne seront dorénavant plus supportés.
[AB#84717](https://devops700.itp.extra/700/TPM/_workitems/edit/84717)

**Comment by Ghost3044** [comment]
Doit avoir été monté en IT pour le 15 aout

**Comment by loima02** [comment]
C'est en PROD!

**Comment by loima02** [comment]
BREAKING - Le retrait du support des fichiers ODT est en IT!

**Comment by loima02** [comment]
BREAKING - Le retrait du support des fichiers ODT est en PROD!
