### ISSUE TITLE
Problème avec la validation des comptes bancaires

### ISSUE THREAD

**Issue by Ghost3044** [MTESSDev/FRW#284]
**Description du problème**
Certains comptes bancaires ne fonctionnent pas.

**Comportement attendu**
J'aimerais que les comptes bancaires fonctionnent. Même ceux de CIBC parce que c'est une banque grandement utilisée au Québec.

[AB#88244](https://devops700.itp.extra/700/TPM/_workitems/edit/88244)

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
