### ISSUE TITLE
IT - Perte de données lors de l'ouverture de l'outil d'essais

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/FRW#286]
**Description du problème**
Nous utilisons un formulaire ouvert à partir d'un lien de reprise. La sauvegarde automatique des données entre les pages ne fonctionne plus. Quand on utilise le lien "outil de développement" les donnes saisies sont perdues. Mais si on click sur "Enregistrer" avant, les données restent. 

**Étapes pour reproduire le bogue**
1) ouvrir un formulaire à partir du lien de reprise
2) commencer la saisie et naviguer vers une autre page
3) cliquer sur le lien outil de développement en bas à droite 
4) toutes nouvelles saisie sont perdu (les données enregistrées avant la réouverture sont remise en place)

**Comportement attendu**
les données saisie restent

**Appareil utilisé/fureteur utilisé**
 - OS:  Windows 10
 - Fureteur: Edge
  
  **Autres informations**
  - Version de l'application FRW : 2024.09

[AB#89671](https://devops700.itp.extra/700/TPM/_workitems/edit/89671)

**Comment by vinnyboii** [comment]
Bonjour,
Un correctif est déjà en cours là-dessus. Il s'agit d'une regression suite à la correction de l'issue #269 en IT.

Ce sera monté sous peu!
Merci

**Comment by vinnyboii** [comment]
Bonjour, 
Est-ce que le problème est réglé? Si oui vous pouvez fermer l'issue.

Merci!

**Comment by jpbeaulieu1** [comment]
C'est bon. Merci
