### ISSUE TITLE
Ajout d'une nouvelle institution financière 703 dans la liste

### ISSUE THREAD

**Issue by Andrea-RetQc** [MTESSDev/FRW#287]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Non, il s'agitd'une demande d'amélioration puisque du côté de Retraite Québec, nous acceptons maintenant une nouvelle institution bancaire dans nos services en ligne (WealthSimple)

**Décrivez votre besoin**
L'institution WealthSimple doit être ajoutée dans les comptes bancaires acceptés par retraite Québec. Cette fonctionnalité est actuellement utilisée dans le formulaire LPF-800 (non gradué en production)

La nouvelle institution est : Wealthsimple Investments Inc., numéro de l’institution est 703 avec numéro de compensation 003. (voir le lien ci-joint de la demande)

**Décrivez les alternatives que vous avez envisagées**
Ajouter l'institution à la liste déjà existante

**Propostion de solution**
Si vous aviez une idée en tête, écrivez là ici.

**Contexte supplémentaire**
Au besoin, communiquez avec moi (Andréa Roy - andrea.roy@retraitequebec.gouv.qc.ca)

[AB#89819](https://devops700.itp.extra/700/TPM/_workitems/edit/89819)

**Comment by Ghost3044** [comment]
Bonjour,

Serait-il possible de nous fournir le lien que vous faites référence dans votre demande SVP? Cela nous aiderait à trouver la bonne solution à votre besoin.

Merci et bonne journée,

**Comment by Andrea-RetQc** [comment]
Bonjour !
Le lien faisait référence à une courriel avec les infos de l'institution bancaires. Je viens de le recopier plus bas. Il y a une image, mais je ne sais pas si ça va fonctionner. Écrivez-moi par courriel au besoin.

Merci !

Il faudrait ajouter une nouvelle institution financière afin de permettre le dépôt direct à nos clients. 

La nouvelle institution est : Wealthsimple Investments Inc., numéro de l’institution est 703 avec numéro de compensation 003. (voir le lien ci-joint de la demande)

![image](https://github.com/user-attachments/assets/82af6e97-8364-4ba1-adca-9bfd5d27a82b)


 

N’hésite pas si besoin d’informations supplémentaires.

**Comment by anisite** [comment]
Bon matin, la seule succursale connue de Wealthsimple semble être la 00001, mais l'institution est bien supportée par FRW 
![image](https://github.com/user-attachments/assets/fde52d68-588b-4510-8011-f41741bec9e4)
avez-vous un enjeu avec cette banque que je ne saisis pas ?

**Comment by Andrea-RetQc** [comment]
Génial !
Nous avons effectivement des enjeux avec cette institution pour l'ajouter dans nos services en ligne. Le paramétrage n'a pas été fait (les tables sont plutôt vieilles :-) )pour accepter des "institutions" qui sont plutôt des Fonds de placement.
Mais tant mieux si c'est fonctionnel de votre côté.
Merci !
