### ISSUE TITLE
Fin anormale DEPOT GED

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#292]
**Description du problème**
Un agent GED reçoit une fin anormale lors de la transmission de son formulaire "DEPOT".

**Étapes pour reproduire le bogue**
1. Aller à FORM DEPOT
2. le remplir
3. Cliquer sur soumettre
4. BANG!

**Comportement attendu**
Le formulaire devrait se transmettre avec succès et afficher la page de confirmation au lieu de l'erreur de fin. (HTTP 502 dans les logs)

**Captures écran**
![image](https://github.com/user-attachments/assets/baa4a6dd-9bb5-4bc4-8c12-27a2130bdf58)

**Appareil utilisé/fureteur utilisé**
S.O.

**Autres informations**
Le problème provient de CloudFront, les headers dépassent le max de 10 204.

[AB#90660](https://devops700.itp.extra/700/TPM/_workitems/edit/90660)

**Comment by anisite** [comment]
Tel que discuté avec Mme Gauthier, j'ajoute cette story au sprint actuel.

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
