### ISSUE TITLE
Modifications libellés pour l'inscription au dépôt direct

### ISSUE THREAD

**Issue by Andrea-RetQc** [MTESSDev/FRW#293]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Des libellés dans le module d'inscription au dépôt direct ne sont pas conformes avec nos autres interfaces ou représentent un terme non adéquat

**Décrivez votre besoin**
C'est "Établissement financier" qui doit être privilégié à "institution financière". (En anglais : "Financial institution")
Le terme "argent propre" devra aussi être supprimé.
![image](https://github.com/user-attachments/assets/be80828c-9bb7-42a0-bfb3-1b16bc3b92a5)

**Décrivez les alternatives que vous avez envisagées**
Aucune, les libellés doivent être modifiés.

**Propostion de solution**
Voir plus haut pour la suppression d'un terme et la modification à un autre.

**Contexte supplémentaire**
Demande portail VPSC (Retraite Qc) : https://saaprod/soutien_tache/outils/portail_vpsc/details-demande.asp?demande=119424#pid=3

[AB#90935](https://devops700.itp.extra/700/TPM/_workitems/edit/90935)

**Comment by Ghost3044** [comment]
Bonjour, 

Lors de nos rencontres d'arrimage avec Retraite Québec, nous avions convenu d'utiliser le terme « institution financière », qui est celui actuellement en place. Maintenant que le développement est terminé, nous avons décidé de conserver cette formulation telle quelle, conformément aux discussions que j'avais eues avec les personnes de l'équipe de dev, où nous avions conclu que cette approche était satisfaisante.

En ce qui concerne le terme « argent propre », il ne s'agissait que d'un exemple dans l'interface. Cette section est entièrement configurable, et vous avez la possibilité de modifier le texte selon vos besoins.

N'hésitez pas si vous avez d'autres questions ou besoins supplémentaires.
