### ISSUE TITLE
Courriel de reprise ne fonctionne plus depuis le 3 octobre en IT

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/FRW#298]
**Description du problème**
Depuis le 3 octobre les courriels de reprise et les courriels pour les utilisateurs suivant ne sont plus envoyé en IT. 

**Étapes pour reproduire le bogue**
1. Ouvrir un formulaire 
2. Enregistrer/ envoyer au prochain utilisateur
3. Attendre sans fin le courriel de reprise

**Comportement attendu**
Les courriel sont envoyés

**Autres informations**
 J'ai parler avec @loima02 qui m'a dit que c'était un problème avec CAC.Courriel et qu'il leur transférait le problème

**merci**

[AB#91764](https://devops700.itp.extra/700/TPM/_workitems/edit/91764)

**Comment by Ghost3044** [comment]
Bonjour, 

Selon notre info, ça devrait fonctionner. À quand remonte la dernière fois que vous avez essayé ? Pourriez-vous nous fournir l'heure ?

Bonne journée,

**Comment by jpbeaulieu1** [comment]
Bonjour
J'ai fais un test ce matin juste avant d'ouvrir ce bug. Et je viens d'en refaire un avec non adresse rbq.gouv.qc.ca. Formulaire REIBH00.

Formulaire transmis.
Votre numéro de confirmation de transmission est le 792252311.
2024-10-15 13:24:53

**Comment by LarcM7** [comment]
typeDemandeAiguillage :)

**Comment by jpbeaulieu1** [comment]
Oups en effet. Désolé.

Merci
