### ISSUE TITLE
Panne en environnement IT

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#303]
Il y a une panne en IT actuellement, vous pouvez suivre l'évolution ici : https://status.infologique.net/status/mess les équipes sont sur le dossier actuellement, merci et désolé des conséquences. 

[AB#93029](https://devops700.itp.extra/700/TPM/_workitems/edit/93029)

**Comment by loima02** [comment]
Nous travaillons toujours sur la panne en environnement IT. Nous vous aviserons lorsque ce sera résolu.

**Comment by loima02** [comment]
La panne est présentement résolue. Nous surveillons l'environnement IT de près et nous fermerons l'issue si tout est encore beau demain.

Merci pour votre compréhension.
