### ISSUE TITLE
Même si nous retirons le selecteur de langue il réapparait dans la page de confirmation

### ISSUE THREAD

**Issue by MJMESS** [MTESSDev/FRW#304]
Bonjour, 

même si la config est formulaireUnilingue: true, lors de l'affichage de la page de confirmation, il apparait à nouveau. 
Nous avons du texte supplémentaire dans la confirmationTransmission.
Exemple :

![image](https://github.com/user-attachments/assets/3b64278e-eea2-49e4-ba85-6ff1f28ffecf)

Le formulaire s'affiche sans le selecteur de langue jusqu'à la soumission. 
Lorsque la page de confirmation s'affiche, le selecteur de langue apparait.

**Étapes pour reproduire le bogue**
1. Mettre la configuration formulaireUnilingue: true
2. Ajouter du texte supplementaire pour la confirmation de transmission
3. Soumettre le formulaire
4. La page de confirmation s'affiche avec le selecteur de langue

**Comportement attendu**
Que le sélecteur de langue n'apparaisse pas à la page de confirmation.

Est-ce normal, est-ce une autre configuration que nous devons ajouter ? 

Merci à l'avance,

 

[AB#93497](https://devops700.itp.extra/700/TPM/_workitems/edit/93497)

**Comment by loima02** [comment]
C'est en IT!

**Comment by MJMESS** [comment]
Merci beaucoup!

**Comment by j0ber** [comment]
Livré 2024.12
