### ISSUE TITLE
Transmission possible en synchrone et au combien de temps les transmissions sont elles traitées

### ISSUE THREAD

**Issue by MJMESS** [MTESSDev/FRW#310]
Nous avons utilisé un formulaire FRW pour un questionnaire qui lorsque soumis fait apparaitre des informations à l'écran en fonction des informations transmises via le formulaire FRW. Dans l'idéal, pour cette utilisation, nous aimerions avoir accès à une transmission synchrone, selon votre documentation ce n'est pas possible. 

Est-ce que vous prévoyez éventuellement avoir une config qui permettrais d'avoir la transmission de façon synchrone ?

Autre question, nous imaginons que vous avez un traitement qui roule et traite les transmissions, est-ce possible de nous informer au combien de temps roule votre traitement pour traiter les transmissions ?

Merci à l'avance! 

[AB#95427](https://devops700.itp.extra/700/TPM/_workitems/edit/95427)

**Comment by Ghost3044** [comment]
Bonjour,

FRW utilise une file de messages lue en continu, ce qui permet un traitement quasi instantané après la soumission. Nous n’avons pas prévu d’ajouter une configuration pour les transmissions synchrones à court terme, car les performances actuelles répondent à la majorité des besoins.

Les transmissions sont traitées en continu. Les délais, s'il y en a, sont généralement dus à des documents en cours de traitement, mais cela reste très rapide.

Merci,
