### ISSUE TITLE
Documentation P700 - Personnalisation de la page révision

### ISSUE THREAD

**Issue by j0ber** [MTESSDev/FRW#41]
Faire une page afin d'expliquer les personnalisations possibles de la page révision (texte ou html avant le bouton "Valider", et texte ou html avant le bouton "Soumettre".

Démontrer la possibilité de modifier le texte du bouton "Soumettre.

Expliquer la révision automatique ou avec le bouton et exemple de bloc de code config.

AB#54789

**Comment by vinnyboii** [comment]
sync azure
