### ISSUE TITLE
Documentation P700 - Fichiers - Ajouter types supportés + params défaut

### ISSUE THREAD

**Issue by j0ber** [MTESSDev/FRW#43]
[AB#73290](https://devops700.itp.extra/700/TPM/_workitems/edit/73290)

**Comment by anisite** [comment]
en lien avec #2

**Comment by vinnyboii** [comment]
sync azure

**Comment by Ghost3044** [comment]
J'ai fait moi-même les ajustements. J'ai fait mon premier commit. 🎉
