### ISSUE TITLE
Problème avec les fichiers xslx ils ne sont plus présent lorsque nous reprenons la saisie d'un formulaire

### ISSUE THREAD

**Issue by MJMESS** [MTESSDev/FRW#47]
### Discussed in https://github.com/MTESSDev/FRW/discussions/44

<div type='discussions-op-text'>

<sup>Originally posted by **MJMESS** April  3, 2023</sup>
Bonjour, 

voici comment reproduire la situation : 

1. Je débute un formulaire
2. Je téléverse des fichiers dont certain de types xlsx
3. Je quitte
4. Je reprend le formulaire,
5. Tous les fichiers de type xlsx ne sont plus présent, un message d'erreur s'affiche.

![image](https://user-images.githubusercontent.com/122536311/229601349-4493d5f1-0e7b-48cb-bc44-6e60d9f7a6ed.png)

Merci à l'avance!</div>

**Comment by anisite** [comment]
@vinnyboii tu confirme ?

**Comment by vinnyboii** [comment]
@j0ber peux-tu vérifier si cette erreur là est dans le contrôle de PJ ?
![image](https://user-images.githubusercontent.com/128411313/229615488-336588ff-8006-4042-ba73-3d2221e401f9.png)

Le fichier XLSX est encore dans le modèle de données suite à la reprise.
![image](https://user-images.githubusercontent.com/128411313/229615305-5cec1029-08c2-446a-b6a0-acbb989c46c3.png)

**Comment by j0ber** [comment]
Le problème a été corrigé.

C'est dans la release [2023.3](https://github.com/MTESSDev/FRW/releases/tag/2023.3-IT).
