### ISSUE TITLE
Problème de rendu d'un textarea sur document Word

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#51]
![image](https://user-images.githubusercontent.com/122536311/229797652-f6e87ac4-a80b-43c5-9ee0-a9fbf40cd338.png)

_Originally posted by @MJMESS in https://github.com/MTESSDev/FRW/discussions/46#discussioncomment-5520808_

[AB#73264](https://devops700.itp.extra/700/TPM/_workitems/edit/73264)

**Comment by anisite** [comment]
@vinnyboii Est-ce qu'on s'ajoute une option pour ajouter un saut de ligne sur certains champs dans le binding ? Ou on ajoute systématiquement une ligne blanche \n sur tous les textarea dans un word ?

**Comment by anisite** [comment]
pour laisser les gens activer ou non l'option on devrait ajouter un mode ? 

ajouterLigneBlancheSurTypes:
   - textarea

ou pour l'instant c'est par défaut et on verra plus tard pour offrir l'option de désactiver au besoin ?

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
