### ISSUE TITLE
Bug avec bac-à-sable en validation auto. sur sauvegarde section Révision

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#52]
Repo steps:

- Mettre la sauvegarde à auto : 
````yaml
  revision:
    validationAutomatique: true    
````
- aller sauvegarder en positionnant le curseur sur la section révision:

![image](https://user-images.githubusercontent.com/3194288/230097921-560f9c21-a774-4344-a787-2e8aedb2f06f.png)

raison: 

> La validation serveur est impossible en mode bac à sable.

**Comment by anisite** [comment]
Fait intéressant, impossible de faire X sur la popup d'erreur technique... y'a un backdrop par dessus ?

**Comment by j0ber** [comment]
Corrigé avec la [release 2023.5-IT](https://github.com/MTESSDev/FRW/releases/tag/2023.5-IT).
