### ISSUE TITLE
Pré-remplissage d'un champ textarea avec sauts de lignes non fonctionnel

### ISSUE THREAD

**Issue by MJMESS** [MTESSDev/FRW#55]
### Discussed in https://github.com/MTESSDev/FRW/discussions/46

Utiliser le service (SIS) en pré-remplissant un champ de type "textarea" en fournissant ceci en pré-remplissage : 
123, rue de l'Organisme\nTrois-Rivières (Québec)\nG1G 1G1

Normalement les \n devraient se traduire par des sauts de ligne une fois le formulaire rendu.

Ce n'est pas le cas. Il sont rendus en texte :  
123, rue de l'Organisme\nTrois-Rivières (Québec)\nG1G 1G1

Comme si le SIS "escapait" les \.

![image](https://user-images.githubusercontent.com/122536311/230175494-1494a214-3c43-40b6-b4c6-82d899aa959c.png)

**Comment by anisite** [comment]
@j0ber est-ce que j'ai vraiment quelque chose à faire ?

**Comment by anisite** [comment]
@MJMESS pourriez vous démarrer un formulaire avec le cas en erreur (depuis votre API actuelle) et nous donner ici l'id publique de formulaire svp ? (ou celui de session, selon ce que vous avez) je n'arrive pas à reproduire le cas via swagger. 

Si vous avez aussi un brakepoint sur votre call à l'api, est-ce possible de faire un dump du contenu json complet qui est envoyé chez nous par l'api SVP ?

**Comment by MJMESS** [comment]
Désolé, erreur de notre côté en regardant le retour du JsonConvert.SerializeObject, en visualisant en format JSON je voyais que l'information semblait être ok mais en visualisant en text j'ai remarqué qu'il ajoutait un \ automatiquement. J'ai donc ajouté un Replace("\\n", "\n") suite à JsonConvert.SerializeObject et maintenant ça fonctionne.
