### ISSUE TITLE
Message d'erreur, mais ça fonctionne

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#62]
### Discussed in https://github.com/MTESSDev/FRW/discussions/61

<div type='discussions-op-text'>

<sup>Originally posted by **jodionrq** April 18, 2023</sup>
Bonjour,
Dans VSCode j'ai un message d'erreur soulignée en rouge pour une commande de validation de date. Mais dans le bac-à-sable, tout semble fonctionner parfaitement. Voir capture d'écran. Le message d'erreur apparait comme attendu. 
![image](https://user-images.githubusercontent.com/124822406/232897931-21e7439a-9990-4c98-8dfd-24ad7fd21d6a.png)

Si j'entre l'information comme il faut, tout fonctionne aussi
![image](https://user-images.githubusercontent.com/124822406/232898296-4aa93d41-665b-46b7-bb48-235f10bdfcfd.png)

Est-ce que ça peut causer problème? Est-ce qu'il y a une autre commande à utiliser? Merci!</div>

AB#53996

**Comment by j0ber** [comment]
Le schema json a été ajusté. Cet avertissement (ainsi que certains autres liés à d'autres validations) ne seront plus affichés.
