### ISSUE TITLE
Ajout la possibilité de supprimer le dossier d’un formulaire déjà déployé au MESS (dossier de config d'un formulaire)

### ISSUE THREAD

**Issue by atifmohamed** [MTESSDev/FRW#64]
### Discussed in https://github.com/MTESSDev/FRW/discussions/54

<div type='discussions-op-text'>

<sup>Originally posted by **MJMESS** April  5, 2023</sup>
Bonjour, nous avons déployés plusieurs formulaires, mais certains d'entre eux étaient des essais et ne seront pas utilisés, est-ce qu'il y a un moyen de les supprimer afin d'épurer ?

Je ne parle pas de supprimer le formulaire d'un individu mais de supprimer le dossier avec le fichier form.yml, bind.yml et transmission.yml de certain formulaire afin qu'ils n'apparaissent plus dans l'outil pour les essais.

Merci à l'avance,</div>

[AB#72779](https://devops700.itp.extra/700/TPM/_workitems/edit/72779)

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!

**Comment by drogu02** [comment]
Est-ce qu'il y a un endroit qui explique comme l'on peut faire pour supprimer un vieux dossier?

**Comment by vinnyboii** [comment]
> Est-ce qu'il y a un endroit qui explique comme l'on peut faire pour supprimer un vieux dossier?

Désolé on avait oublié de mentionner que ça avait été mis à jour dans la documentation de déploiement ici: https://github.com/MTESSDev/azurepipeline-mtess-frw-deploiement/tree/main#nettoyage
