### ISSUE TITLE
[Bac-à-sable] Mauvaise page sélectionnée lors de la navigation sur une page avec prefixId

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#66]
**Description du problème**
Lors d'une sauvegarde `CTRL+S` dans le bac-à-sable, la page affichée n'est pas la bonne dans certains cas.

**Étapes pour reproduire le bogue**
1. Choisir une section de config form avec un prefixID (adulte1)
2. Positionner le curseur et faire `CTRL+S`
3. L'écran s'affiche à la page 0 par erreur

**Comportement attendu**
Le prefix devrait être considéré et la bonne page devrait s'afficher.

**Captures écran**
![image](https://user-images.githubusercontent.com/3194288/233664855-ae9aa8db-793d-45dd-8c05-8d25cb5f400c.png)
SectionParent ne contient pas le nom complet avec le prefixID lors de la boucle il faudrait l'ajouter.

**Appareil utilisé/fureteur utilisé**
 - N/A

**Autres informations**
- Version de l'application FRW : toutes les versions

AB#54093

**Comment by loima02** [comment]
C'est en PROD!
