### ISSUE TITLE
Problème avec la migration d'un formulaire vers IT et PROD

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#72]
Je ne suis pas en mesure de pousser l'un de mes formulaires en IT et en PROD avec Devops.

Mon formulaire est dans le répertoire Personnes-immigrantes sur 700 / SSCW

Ça fait ce problème parfois avec les formulaires que j'ai un gabarit word custom.

Ça fonctionnait mais ça ne fonctionne plus.

Message: System.Management.Automation.CmdletInvocationException: La connexion sous-jacente a été fermée : Une erreur inattendue s'est produite lors de l'envoi. ---> System.Net.WebException: La connexion sous-jacente a été fermée : Une erreur inattendue s'est produite lors de l'envoi. ---> System.IO.IOException: Impossible d'écrire les données sur la connexion de transport : Une connexion existante a dû être fermée par l’hôte distant. ---> System.Net.Sockets.SocketException: Une connexion existante a dû être fermée par l’hôte distant 
à System.Net.Sockets.Socket.MultipleSend(BufferOffsetSize[] buffers, SocketFlags socketFlags)
à System.Net.Sockets.NetworkStream.MultipleWrite(BufferOffsetSize[] buffers)
--- Fin de la trace de la pile d'exception interne ---
à System.Net.Sockets.NetworkStream.MultipleWrite(BufferOffsetSize[] buffers)
à System.Net.Security._SslStream.StartWriting(SplitWritesState splitWrite, SplitWriteAsyncProtocolRequest asyncRequest)
à System.Net.Security._SslStream.ProcessWrite(BufferOffsetSize[] buffers, SplitWriteAsyncProtocolRequest asyncRequest)
à System.Net.TlsStream.MultipleWrite(BufferOffsetSize[] buffers)
à System.Net.Connection.Write(ScatterGatherBuffers writeBuffer)
à System.Net.ConnectStream.ResubmitWrite(ConnectStream oldStream, Boolean suppressWrite)
--- Fin de la trace de la pile d'exception interne ---
à Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
à Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
--- Fin de la trace de la pile d'exception interne ---
à System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
à System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
à System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
à System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)

AB#54366

**Comment by vinnyboii** [comment]
@loima02  @anisite

**Comment by vinnyboii** [comment]
@drogu02 peux tu nous fournir les informations suivantes svp?

1. Screenshot de l'erreur
2. nom de tes fichiers
3. log de ton déploiement
4. La grosseur de l'artéfact produit par le build dans les logs du déploiement
5. Est-ce que le problème survient systématiquement à chaque fois ou si tu réessaies plusieurs fois ça fini par passer?
6. Est-ce que le problème survient pour tous les formulaires qui ont un gabarit Word d'associé?

**Comment by drogu02** [comment]
![Erreur](https://user-images.githubusercontent.com/43148349/234876025-814b390c-fe52-4f8a-a0dd-b50f86ab6984.png)
![Artifacts](https://user-images.githubusercontent.com/43148349/234876027-7c2ce97c-f5df-47d9-883f-566ae62d90e3.png)
[tasklog_8.log](https://github.com/MTESSDev/FRW/files/11344038/tasklog_8.log)

1. Screenshot de l'erreur   **(Voir  image Erreur)**
3. nom de tes fichiers  **(Voir  image Artifacts)**
4. log de ton déploiement **(Voir le log)**
5. La grosseur de l'artéfact produit par le build dans les logs du déploiement  **Les fichiers pèsent 170 Ko ensemble, l'artéfact semble être de 1 Mo. Voir image Artifacts**
6. Est-ce que le problème survient systématiquement à chaque fois ou si tu réessaies plusieurs fois ça fini par passer?  **Ça ne passe jamais. Il m'est arrivé dans le passé que ça passe en réessayant, mais ce n'était peut-être pas le même problème.**
7. Est-ce que le problème survient pour tous les formulaires qui ont un gabarit Word d'associé?  **J'ai fait un test avec un autre. Pour l'autre, ça l'a passé en IT du premier coup, mais ça ne passe pas en prod.    Tandis que lui en lien avec cet issue ne fonctionne pas en it et en prod.  Donc ça semble vraiment lié au fichier de gabarit word.**

**Comment by drogu02** [comment]
[erreur_prod.log](https://github.com/MTESSDev/FRW/files/11344353/erreur_prod.log)
Voici le log de la prod qui ne fonctionne pas non plus pour l'autre formulaire.

**Comment by anisite** [comment]
Actuellement les tests ont montrés que le problème est en lien avec les serveurs de build APP18 et APP19, ça a été reproduit manuellement. Une demande a été envoyée au MCN, la théorie est qu'il s'agirait d'un problème avec Fortigate. à suivre.

**Comment by loima02** [comment]
Avec l'aide du MCN, l'incident semble résolu.
Je laisse le billet ouvert jusqu'à lundi. @drogu02, merci de m'informer si l'erreur revient!

**Comment by drogu02** [comment]
Oui ça fonctionne maintenant! Merci!
