### ISSUE TITLE
Amélioration du contrôle d'adresse

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#74]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Le rapport des tests d'accessibilité a montré une lacune avec le contrôle d'adresse:

La notion "Effectuer une nouvelle recherche" ne semble pas claire. Revoir le concept.
Extrait du rapport d'accessibilité : Supprimer l’adresse complète du texte caché du bouton de l’icône de loupe et ne laisser que « Effectuer une nouvelle recherche ». Rassembler l’adresse complète et ensuite « Effectuer une nouvelle recherche » fait que la majorité des participants naviguent rapidement et ne lient pas le reste du texte caché. Par contre voir ce qu'on fait pour la lecture de l'adresse complète.

**Décrivez votre besoin**
Rendre le concept de nouvelle recherche plus évident dans le contrôle d'adresse

**Décrivez les alternatives que vous avez envisagées**
rien

AB#54958

**Comment by j0ber** [comment]
Livré avec la version [2023.6](https://github.com/MTESSDev/FRW/releases/tag/2023.6).
