### ISSUE TITLE
Problème en lien avec une condition sur un checkbox  et un champ hidden

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/FRW#81]
J'ai trouvé un petit problème en lien avec une condition sur un checkbox 

Une copie de mon formulaire Référencement-Entreprises avec le problème a été mis sur l'environnement Satellite.

La case à cochée est non cliquable si le champ suivant est un champ hidden.

Cette issue peut-être assignée à Vincent, il est déjà au courant.

AB#55445

**Comment by j0ber** [comment]
C'est en PROD
