### ISSUE TITLE
Formulaire transmis sans numéro de confirmation dans la BD

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#82]
**Description du problème**
Dans le système ECS, à deux reprises le numéro de confirmation a disparu de la BD suite à la transmission du formulaire.
Cela a eu pour impact d'associer les documents déposés dans la GED au numéro de confirmation "-1".
Dans la BD, on peut voir qu'il y a eu un suivi MAJ quelques millisecondes après le TRANSMIS. 
Les deux occurrences du problème se sont produites en février 2022 et avril 2023.

**Étapes pour reproduire le bogue**
Le bug 23365 avait été créé durant le projet, mais il avait été fermé faute de ne pas être capable de le reproduire.

**Comportement attendu**
Le numéro de confirmation ne doit pas être écrasé à la transmission.

**Captures écran**
Voir PJ de la story dans Azure.

[AB#73246](https://devops700.itp.extra/700/TPM/_workitems/edit/73246)

**Comment by anisite** [comment]
El problema ha vuelto

**Comment by anisite** [comment]
test 2

**Comment by loima02** [comment]
En PROD depuis le 2024-02-07
