### ISSUE TITLE
Page de paiement avec Monéris

### ISSUE THREAD

**Issue by ydion017** [MTESSDev/FRW#83]
### **Programme ANCRÉ - plateforme des registres de l'état**

**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
NON

**Décrivez votre besoin**
Un citoyen doit faire une demande auprès d'un registre, comme celui de l'État Civil, pour obtenir un document officiel. C'est généralement un service payant et le citoyen doit faire le paiement au moment de faire sa demande, idéalement directement dans le formulaire de demande.

**Décrivez les alternatives que vous avez envisagées**
La plateforme ANCRÉ deviendrait responsable du paiement Moneris APRÈS qu'un formulaire soit soumis, ce qui n'est pas l'idéal.

**Propostion de solution**
Idéalement, FRW permettrait l'ajout d'une page de paiement avec Moneris. Si le paiement n'est pas effectué ou si le paiement est refusé, le formulaire ne devrait pas pouvoir être soumis. Il s'agirait d'une condition obligatoire. Dans le cas où le paiement est effectué avec succès, les infos de confirmation du paiement seraient retournées avec les données du formulaire.

**Contexte supplémentaire**
Un document détaillé sur l'intégration de Moneris a déjà été envoyé à l'équipe

[AB#73301](https://devops700.itp.extra/700/TPM/_workitems/edit/73301)

**Comment by ydion017** [comment]
Lorsque l’utilisateur fait un paiement avec Moneris, ce serait important que les info de confirmation soient envoyées au système autorisé même si le formulaire n'est pas soumis. Un remboursement pourrait devoir être fait.

**Comment by anisite** [comment]
il y a le schéma form à ajuster

**Comment by j0ber** [comment]
je l'avais fait

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
