### ISSUE TITLE
Créer un schéma pour le PIV

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#95]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
Non.

**Décrivez votre besoin**
Il faudrait créer un fichier schema pour décrire les éléments du PIV.

**Décrivez les alternatives que vous avez envisagées**
Aucune.

**Propostion de solution**
Il faudrait créer un fichier schema comme pour le type form.

AB#57229

**Comment by j0ber** [comment]
C'est en PROD
