### ISSUE TITLE
Pouvoir rechercher dans le P700

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#96]
**Votre demande de fonctionnalité est-elle liée à un problème ? Si oui, veuillez décrire.**
NON

**Décrivez votre besoin**
On voudrait pouvoir rechercher dans le P700.

**Décrivez les alternatives que vous avez envisagées**
Passer les sections une par une mais c'est long.

**Propostion de solution**
Un champ de recherche svp.

AB#57260

**Comment by anisite** [comment]
C'est en IT

**Comment by loima02** [comment]
C'est en PROD
