### ISSUE TITLE
Caractère ``"`` fait planter les domaines de valeurs

### ISSUE THREAD

**Issue by anisite** [MTESSDev/FRW#97]
**Description du problème**
Le caractère ``"`` crée une fin anormale.

**Étapes pour reproduire le bogue**
1. Ajouter un domaine dans une config
2. y mettre un libellé avec un ``"``
3. planter

**Comportement attendu**
ça devrait être escapé

**Captures écran**
Si applicable, des captures d'écran démontrant le problème.

**Appareil utilisé/fureteur utilisé**
 - OS: (ex: Windows 10)
 - Fureteur: (ex: Chrome 111)

**Autres informations**
- Version de l'application FRW (inscrite au bas de la page) 2023.5

AB#57297

**Comment by j0ber** [comment]
Livré avec la version [2023.6](https://github.com/MTESSDev/FRW/releases/tag/2023.6).
