### ISSUE TITLE
Gérer la transmission du formulaire dans un courriel

### ISSUE THREAD

**Issue by vinnyboii** [MTESSDev/FRW#99]
**Décrivez votre besoin**
On aimerait que la solution FRW ait une fonctionnalité pour transmettre le fichier produit par FRW contenant les données du formulaire pour faciliter l'utilisation par des systèmes qui n'ont pas de back end pour gérer la transmission.

**Décrivez les alternatives que vous avez envisagées**
Actuellement, les systèmes autorisés doivent se créer un API pour recevoir les données du formulaire et gérer le traitement de ces données.
Si on offre la transmission du fichier produit, cela serait un minimum qui pourrait faciliter l'utilisation de FRW.

[AB#72780](https://devops700.itp.extra/700/TPM/_workitems/edit/72780)

**Comment by loima02** [comment]
C'est en IT!

**Comment by loima02** [comment]
C'est en PROD!
